import {StyleSheet} from 'react-native';
import {SCREEN_WIDTH,SCREEN_HEIGHT} from '../../constants/common';
import {LIGHT_GRAY,APP_COLOR,LIGHT_GRAY_TAB,BUTTON_COLOR,FACEBOOK_HEX} from '../../constants/colors'

export const STYLES=StyleSheet.create({
  topSearchNav:{
    backgroundColor:APP_COLOR,
    height:SCREEN_HEIGHT/5,
    width:SCREEN_WIDTH
  },
  horzLine:{
    height:0.6,
    backgroundColor:'lightgray',
    width:SCREEN_WIDTH
  },
  navTitle:{
    marginHorizontal:SCREEN_HEIGHT/50,
    color:'white',
    marginTop:30,
    fontSize:16,
    textAlign:'center',
    fontFamily:"DIN-Regular"
  },
  grayDiv:{
    height:SCREEN_HEIGHT/50,
    marginTop:SCREEN_HEIGHT/50,
    backgroundColor:LIGHT_GRAY,
    width:SCREEN_WIDTH
  },
  profileContainer:{
    height:SCREEN_HEIGHT/4.16,
    backgroundColor:LIGHT_GRAY,
    width:SCREEN_WIDTH
  },
  profile:{
    width:SCREEN_HEIGHT/8.34,
    height:SCREEN_HEIGHT/8.34,
    alignSelf:'center',
    marginTop:SCREEN_HEIGHT/16.6,
    borderRadius:SCREEN_HEIGHT/16.60
  },
  text:{
    marginTop:SCREEN_HEIGHT/50,
    color:'black',
    textAlign:'center',
    fontSize:16,
    marginHorizontal:SCREEN_HEIGHT/50,
    fontFamily:"DIN-Regular"
  },
  icon:{
    marginLeft:SCREEN_HEIGHT/33.3,
    marginTop:SCREEN_HEIGHT/33.3,
    width:SCREEN_HEIGHT/25,
    height:SCREEN_HEIGHT/25,
    alignSelf:'center'
  },
  vertLine:{
    height:SCREEN_HEIGHT/7.14,
    width:0.6,
    backgroundColor:'gray'
  },
  grayDiv:{
    backgroundColor:LIGHT_GRAY,
    height:SCREEN_HEIGHT/62.5,
    width:SCREEN_WIDTH
  },
  rightArrow:{
    marginTop:SCREEN_HEIGHT/33.3,
    width:SCREEN_HEIGHT/33.3,
    height:SCREEN_HEIGHT/33.3,
    alignSelf:'flex-end',
    marginRight:SCREEN_HEIGHT/50
  },
  textfield:{
    marginHorizontal:SCREEN_HEIGHT/33.3,
    marginTop:SCREEN_HEIGHT/50,
    fontSize:14,
    color:'gray',
    fontFamily:"DIN-Regular"
  },
  button:{
    marginHorizontal:SCREEN_HEIGHT/33.3,
    height:44,
    backgroundColor:BUTTON_COLOR,
    marginTop:SCREEN_HEIGHT/12.5,
    justifyContent:'center'
  },
  cardview:{
    height:SCREEN_HEIGHT/5,
    marginLeft:SCREEN_HEIGHT/33.3,
    width:SCREEN_WIDTH-SCREEN_HEIGHT/16.6,
    backgroundColor:LIGHT_GRAY,
    marginTop:SCREEN_HEIGHT/25
  },
  mobile:{
    alignSelf:'center',
    marginTop:SCREEN_HEIGHT/33.3,
    width:SCREEN_HEIGHT/12.5,
    height:40
  },
  bottomButton:{
    left:SCREEN_HEIGHT/33.3,
    width:SCREEN_WIDTH-SCREEN_HEIGHT/16.6,
    height:44,
    backgroundColor:BUTTON_COLOR,
    bottom:SCREEN_HEIGHT/50,
    position:'absolute',
    justifyContent:'center'

  },
  ecommerce:{
    width:SCREEN_WIDTH,
    height:SCREEN_HEIGHT/3.33
  },
  socialBtn:{
    backgroundColor:FACEBOOK_HEX,
    marginTop:SCREEN_HEIGHT/33.3,
    width:SCREEN_WIDTH/2-SCREEN_HEIGHT/25,
    marginLeft:SCREEN_HEIGHT/33.3,
    height:44
  },
  logout:{
    position:'absolute',
    top:31,
    color:'white',
    fontSize:12,
    paddingRight:10,
    alignSelf:'flex-end',
    fontFamily:"DIN-Regular"
  },
  unVerified:{
    width:15,
    height:15,
  },
  map:{
    width:SCREEN_WIDTH,
    height:SCREEN_HEIGHT,
  },
  description:{
    marginHorizontal:SCREEN_HEIGHT/50,
    height:150,
    borderWidth:0.6,
    borderColor:'lightgray',
    marginTop:SCREEN_HEIGHT/33.3,
    fontFamily:"DIN-Regular",
    padding:10
  },
  checkMark:{
    width:18,
    height:18
  },
  buttonTxt:{
    color:'white',
    fontWeight:'bold',
    fontSize:14,
    alignSelf:'center',
    fontFamily:"DIN-Regular",
  },
  verified:{
    marginTop:-30,
    marginRight:SCREEN_HEIGHT/41.6,
    marginLeft:'auto',
    fontSize:13,
    backgroundColor:'#28C2E1',
    color:'white',
    width:55,
    height:18,
    textAlign:'center',
    alignSelf:'flex-end'
  },
  txt:{
    marginLeft:SCREEN_HEIGHT/33.3,
    color:'black',
    marginTop:10,
    fontFamily:"DIN-Regular"
  }
})
