import {StyleSheet,Platform} from 'react-native';
import {SCREEN_WIDTH,SCREEN_HEIGHT} from '../../constants/common';
import {LIGHT_GRAY,APP_COLOR,LIGHT_GRAY_TAB,BUTTON_COLOR} from '../../constants/colors'

export const STYLES=StyleSheet.create({
  tabbar:{
    backgroundColor:LIGHT_GRAY_TAB,
    height:60
  },
  indicator: {
    backgroundColor: APP_COLOR,
    position: 'absolute',
    left: 0,
    bottom: 0,
    right: 0,
    height: 2,
  },
  pdf:{
    width:100,
    height:150,
    alignSelf:'center',
    marginTop:30
  },
  tab:{
    backgroundColor: 'transparent',
    color: APP_COLOR,
    marginTop: 15,
    fontWeight:'bold',
    fontFamily:"DIN-Regular"
  },
  text:{
    marginTop:SCREEN_HEIGHT/50,
    color:'black',
    textAlign:'center',
    fontSize:14,
    marginHorizontal:SCREEN_HEIGHT/50,
    fontFamily:"DIN-Regular"
  },
  icon:{
    marginLeft:SCREEN_HEIGHT/33.3,
    marginTop:15,
    width:22,
    height:22,
    alignSelf:'center'
  },
  vertLine:{
    height:SCREEN_HEIGHT/7.14,
    width:0.6,
    backgroundColor:'gray'
  },
  cardview:{
    marginHorizontal:SCREEN_HEIGHT/100,
    backgroundColor:'white',
    paddingBottom:15
  },
  add:{
    width:40,
    alignSelf:'center',
    height:40,
  },
  bottomText:{
    marginTop:SCREEN_HEIGHT/50,
    fontSize:13,
    color:APP_COLOR,
    fontWeight:"bold",
    width:SCREEN_WIDTH,
    textAlign:'center',
    fontFamily:"DIN-Regular"
  },
  button:{
    left:SCREEN_HEIGHT/33.3,
    width:SCREEN_WIDTH-SCREEN_HEIGHT/16.6,
    height:44,
    backgroundColor:'white',
    borderWidth:1,
    borderColor:BUTTON_COLOR,
    position:'absolute',
    bottom:SCREEN_HEIGHT/25,
    justifyContent:'center'
  },
  textfield:{
    marginHorizontal:SCREEN_HEIGHT/50,
    marginTop:0,
    fontFamily:"DIN-Regular"
  },
  halfTxtField:{
    marginLeft:SCREEN_HEIGHT/50,
    marginTop:0,
    width:SCREEN_WIDTH/2-SCREEN_HEIGHT/33.3,
    fontFamily:"DIN-Regular"
  },
  grayDiv:{
    backgroundColor:LIGHT_GRAY,
    height:SCREEN_HEIGHT/62.5,
    width:SCREEN_WIDTH
  },
  rightArrow:{
    marginTop:10,
    alignSelf:'flex-end',
    marginRight:Platform.OS=="ios"?SCREEN_HEIGHT/50:20,
    marginLeft:'auto'
  },
  horzLine:{
    height:0.6,
    backgroundColor:'lightgray',
    width:SCREEN_WIDTH,
    marginLeft:SCREEN_HEIGHT/50,
    marginTop:SCREEN_HEIGHT/33.3
  },
  categoryImg:{
    marginTop:SCREEN_HEIGHT/33.3,
    marginLeft:SCREEN_HEIGHT/50,
    width:22,
    height:22,
  },
  attach:{
    marginLeft:SCREEN_HEIGHT/50,
    marginTop:SCREEN_HEIGHT/50,
    width:40,
    height:40,
  },
  relativeButton:{
    marginTop:SCREEN_HEIGHT/25,
    marginHorizontal:SCREEN_HEIGHT/50,
    height:44,
    backgroundColor:BUTTON_COLOR,
    justifyContent:'center'
  },
  productDescription:{
    marginHorizontal:SCREEN_HEIGHT/50,
    height:150,
    borderWidth:0.6,
    borderColor:'lightgray',
    marginTop:SCREEN_HEIGHT/33.3,
    fontFamily:"DIN-Regular",
    padding:10
  },
  productBroucher:{
    color:"#7F21EA",
    marginHorizontal:SCREEN_HEIGHT/50,
    marginTop:SCREEN_HEIGHT/100
  },
  smallIcons:{
    marginLeft:SCREEN_HEIGHT/50,
    marginTop:SCREEN_HEIGHT/100
  },
  minQuantity:{
    marginLeft:SCREEN_HEIGHT/100,
    marginTop:SCREEN_HEIGHT/100,
    fontSize:14,
    color:'gray',
    textAlign:'left',
    fontFamily:"DIN-Regular"
  },
  delete:{
    top:SCREEN_HEIGHT/50,
    width:SCREEN_HEIGHT/10,
    height:SCREEN_HEIGHT/10,
    position:'absolute',
    left:SCREEN_HEIGHT/25
  },
  product:{
    width:120,
    height:120,
    alignSelf:'center',
    marginTop:SCREEN_HEIGHT/8.3
  },
  cancel:{
    width:18,
    height:18,
    marginLeft:11
  },
  buttonTxt:{
    color:BUTTON_COLOR,
    fontWeight:'bold',
    fontSize:14,
    alignSelf:'center',
    fontFamily:"DIN-Regular",
  },
  rightAlign:{
    alignSelf:'flex-end',
    marginTop:2,
    marginRight:SCREEN_HEIGHT/50,
    marginLeft:'auto'
  },
  rightAlignTxt:{
    color:BUTTON_COLOR,
    fontFamily:'DIN-Regular',
    fontSize:14,
    fontWeight:'bold'
  },
  deleteIcon:{
    marginRight:SCREEN_HEIGHT/50,
    marginTop:1,
    alignSelf:'flex-end'
  },
  card:{
    marginHorizontal:10,
    backgroundColor:'white',
    marginTop:8,
    borderRadius:0,
    paddingBottom:Platform.OS=="ios"?10:20
  },
  trendingImages:{
    marginLeft:5,
    height:100,
    width:100,
    marginTop:10
  },
  productTitle:{
    marginTop:20,
    fontSize:14,
    color:'black',
    marginLeft:10,
    width:SCREEN_WIDTH-135,
    fontFamily:"DIN-Regular",
  },
  productDscrp:{
    fontSize:13,
    fontFamily:'DIN-Regular',
    color:'gray',
    width:SCREEN_WIDTH-135,
    marginTop:4,
    marginLeft:10,
  },
bigText:{
  marginTop:15,
  fontSize:26,
  fontFamily:'DIN-Regular',
  marginLeft:SCREEN_HEIGHT/50,
  color:'black'
},
  rightChevron:{
    top:10,
    right:Platform.OS=="ios"?SCREEN_HEIGHT/50:20,
    position:'absolute'
  },
  rating:{
    fontSize:13,
    color:'white',
    fontWeight:'bold',
    alignItems:'center',
    marginLeft:3.5,
  },
  swiperImg:{
    height:250,
    width:SCREEN_WIDTH
  },
  swiperContainer:{
    height:265,
    backgroundColor:'white'
  },
  halfWidthTxt:{
    marginLeft:SCREEN_HEIGHT/50,
    color:'gray',
    marginTop:SCREEN_HEIGHT/50,
    fontSize:15,
    fontFamily:"DIN-Regular",
    width:SCREEN_WIDTH/2-SCREEN_HEIGHT/50
  },
  title:{
    marginHorizontal:SCREEN_HEIGHT/50,
    color:'gray',
    marginTop:15,
    fontFamily:"DIN-Regular"
  },
  touchableOpacityContainer:{
    marginTop:SCREEN_HEIGHT/50,
    height:35,
    marginLeft:SCREEN_HEIGHT/50,
    backgroundColor:LIGHT_GRAY,
    alignSelf: 'flex-start',
    borderRadius:4
  },
  btnTitle:{
    margin:SCREEN_HEIGHT/50,
    marginLeft:SCREEN_HEIGHT/50,
    fontSize:13,
    fontFamily:"DIN-Regular",
    color:'black'
  },
  socialIcon:{
    marginTop:12,
    marginLeft:SCREEN_HEIGHT/50,
    width:30,
    height:30
  },
  centerButton:{
    marginTop:10,
    alignSelf:'center',
    height:35,
    backgroundColor:BUTTON_COLOR,
    justifyContent:'center',
    padding:10,
    margin:10,
    borderRadius:4
  }
})
