export const en={
  login:"LOGIN",
  register:"REGISTER",
  username:"Username",
  email:"Email",
  mobile:"Mobile",
  password:"Password",
  confirmPassword:"Confirm Password",
  signup:"SIGNUP",
  otpMessage:"Enter 4-digits OTP sent to your mobile",
  enterOTP:"Enter OTP",
  verify:"VERIFY",
  resendOTP:"Resend Verification OTP",
  emailOrusername:"Email/Username",
  continueWithFb:"CONTINUE WITH FACEBOOK",
  continueWithGoogle:"CONTINUE WITH GOOGLE",
  forgotPassword:"FORGOT PASSWORD?",
  enterMobile:"Enter your registered mobile number",
  verify:"VERIFY",
  trendingProducts:"TOP TRENDING PRODUCTS",
  lightEquipmentTools:"LIGHT EQUIPMENT TOOLS",
  foodProducts:"FOOD & RETAIL PRODUCTS",
  latestProducts:"LATEST PRODUCTS",
  recommendedProducts:"RECOMMENDED PRODUCTS",
  topRatedProducts:"TOP RATED PRODUCTS",
  heavyEquipmentTools:"HEAVY EQUIPMENT TOOLS",
  products:"PRODUCTS",
  suppliers:"SUPPLIERS",
  searchProducts:"Search Products",
  searchSuppliers:"Search Suppliers",
  recentSearches:"Recent Searches",
  popularSearches:"Popular Searches",
  results:"results",
  contact:"Contact",
  productDetails:"PRODUCT DETAILS",
  companyProfile:"Company Profile",
  follow:"FOLLOW",
  visitProfile:"VISIT PROFILE",
  itemDetails:"ITEM DETAILS",
  detailsPicture:"Details Picture",
  recommendedFromThisSupplier:"Recommended from this supplier",
  recommendedFromOtherSupplier:"Recommended from other suppliers",
  sendEnquiry:"SEND ENQUIRY",
  chatNow:"CHAT NOW",
  sendEnquiry:"SEND ENQUIRY",
  attachPhotos:"Attach Photos",
  recommendOtherSuppliers:"Recommend other matching suppliers if this supplier doesn't contact me within 24 hours.",
  agreeToShareContactInfo:"I agree to share my contact information in my Buyer profile with the supplier.",
  send:"SEND",
  accounts:"ACCOUNTS",
  manageOrders:"Manage Orders",
  favourites:"Favourites",
  quotations:"Your Quotations",
  buyingRequest:"Buying Request",
  profileDetails:"Profile Details",
  settings:"Settings",
  aboutUs:"About Us",
  TC:"Terms & Conditions",
  privacyPolicy:"Privacy Policy",
  contactUs:"Contact Us",
  profileDetailsTitle:"PROFILE DETAILS",
  firstName:"First Name",
  lastName:"Last Name",
  contactNumber:"Contact Number",
  changePassword:"CHANGE PASSWORD",
  updateDetails:"UPDATE DETAILS",
  otp:"OTP",
  newPassword:"New Password",
  save:"SAVE",
  language:"Language",
  notifications:"Notifications",
  languageTitle:"LANGUAGE",
  companyName:"Company Name",
  location:"Location",
  logout:'LOGOUT',
  welcome:'Welcome to Brown Eagle',
  loginOrSignup:'Login or signup to like, collect and manage orders',
  continueWith:'CONTINUE WITH',
  fb:'FACEBOOK',
  google:'GOOGLE',
  enterEmail:'Please enter your email address',
  emailSent:'A confirmation email has been sent to your mailbox',
  checkEmail:'Please check your email.',
  resendEmail:'Resend email',
  notReceiveEmail:'Having problem receiving email?',
  clickHere:'Click Here',
  manageProducts:'Manage Products',
  manageProductsTitle:'MANAGE PRODUCTS',
  manageBusiness:'Manage Business',
  allProducts:'All Products',
  approvedProducts:'Approved Products',
  approvedProductsTitle:'APPROVED PRODUCTS',
  approvalPending:'Approval Pending',
  rejectedProducts:'Rejected Products',
  rejectedProductsTitle:'REJECTED PRODUCTS',
  addNewProduct:'ADD A NEW PRODUCT',
  allProductsTitle:'ALL PRODUCTS',
  productNameCannotEmpty:'Product name cannot be empty',
  ok:'OK',
  pleaseEnterKeyword:'Please enter at least one Product Keyword',
  productCatCannotEmpty:'Product category cannot be empty',
  productSubCatCannotEmpty:'Product sub category cannot be empty',
  addProductDescription:'Add a product description',
  productQualityCannotBeEmpty:'Product minimum quantity cannot be empty',
  addProductPrice:'Add a product price',
  basicInformation:'Basic Information',
  productName:'Product Name',
  productKeywords:'Product Keywords',
  catInformation:'Category Information',
  category:'Category',
  searchCat:'Search Categories',
  subCat:'Sub Category',
  productDetailsInformation:'Product Details Information',
  productPhoto:'Product Photo / Video',
  productDescription:'Product Description',
  requirement:'Requirement',
  minQuality:'Minimum Quantity(ex - 10)',
  productPrice:'Product Price',
  submit:'SUBMIT',
  addProductTitle:'ADD PRODUCT',
  cancel:'Cancel',
  fromCamera:'From Camera',
  fromLibrary:'From Library',
  apparel:'Apparel, Textiles & Accessories',
  transportation:'Auto & Transportation',
  electronics:'Electronics',
  machinery:'Machinery, Hardware & Tools',
  gifts:'Gifts, Sports & Hobbies',
  homeLights:'Home, Lights & Construction',
  healthBeauty:'Health & Beauty',
  jewelryBags:'Jewelry, Bags & Shoes',
  electricalEquipment:'Electrical Equipment',
  agriculture:'Agriculture & Food',
  packaging:'Packaging, Advertising & Office',
  rawProcessing:'Raw & Processed Materials',
  Apparel:'Apparel',
  textile:'Textile & Leather Products',
  fashion:'Fashion Accessories',
  automobiles:'Automobiles & Motorcycles',
  Transportation:'Transportation',
  computer:'Computers',
  consumerElectronics:'Consumer Electronics',
  homeAppliances:'Home Appliances',
  security:'Security & Protection',
  hardware:'Hardware & Tools',
  instruments:'Measurement & Analysis Instruments',
  Machinery:'Machinery',
  mechanicalParts:'Mechanical Parts & Fabrication Service',
  giftsCrafts:'Gifts & Crafts',
  sportsEnternainment:'Sports & Entertainment',
  toys:'Toys & Hobbies',
  construction:'Construction & Real Estate',
  lights:'Lights & Lighting',
  homeGarden:'Home & Garden',
  furniture:'Furniture',
  healthMedical:'Health & Medical',
  beautyCare:'Beauty & Personal Care',
  luggageBags:'Luggage, Bags & Cases',
  timePieces:'Timepieces, Jewelry, Eyewear',
  shoesAccessories:'Shoes & Accessories',
  electricalSuppliers:'Electrical Equipment & Supplies',
  elctronicComponents:'Electronic Components & Supplies',
  telecommunications:'Telecommunications',
  agriculture:'Agriculture',
  foodBeverage:'Food & Beverage',
  packagingPrinting:'Packaging & Printing',
  schoolSuppliers:'Office & School Supplies',
  serviceEquipment:'Service Equipment',
  mineralsMetallurgy:'Minerals & Metallurgy',
  chemicals:'Chemicals',
  rubberPlastic:'Rubber & Plastics',
  energy:'Energy',
  environment:'Environment',
  youHaveNotAddedProduct:'You have not added any product yet.',
  pendingProducts:'PENDING PRODUCTS',
  areYouSure:'Are you sure?',
  yes:'Yes',
  update:'UPDATE',
  notApproved:'None of your products has been approved',
  noProductsFound:'No Products found',
  clickToEdit:'Click To Edit',
  haveAnyQues:'If you have any questions about these Terms, please contact us.',
  contact:'CONTACT',
  address:'BROWN EAGLE INC.\n1000 N West Street\nSuite 1200\nWilmington, DE 19801\nPhone Number: 302-295-3816\nFax Number: 302-295-4801',
  registeredAddress:'Registered Address',
  Address:'Address',
  city:'City',
  state:'State',
  zipCode:'Zip Code',
  country:'Country',
  operationalAddress:'Operational Address',
  companyInfo:'Company Information',
  website:'Website(ex: http://www.example.com)',
  established:'Established',
  employeeCount:'Employee Count',
  description:'Company Description',
  emailNotVerified:'EMAIL NOT VERIFIED',
  verifyNow:'Click VERIFY  to verify your BrownEagle account',
  later:'Later',
  mainProducts:'Main Products',
  add:'ADD',
  keywordsEx:'(eg: Keyword1, Keyword2, Keyword3)',
  settingsTitle:'SETTINGS',
  TCTtile:'TERMS & CONDITIONS',
  contactUsTitle:'CONTACT US',
  profileNotVerified:'PROFILE VERIFICATION PENDING',
  ok:'OK',
  sameAsRegisteredAddress:'Same as registered address',
  passwordResetMsg:'To reset your password, an email has been sent to your mailbox',
   account:'Account',
  payment:'Payment',
  sales:'Sales',
  support:'Support',
  others:'Others',
  chooseDepartment:'Choose Department',
  message:'Message...',
  rfqTitle:'BUYING REQUEST',
  searchRfq:'Search RFQ',
  rfqDetailsTitle:'RFQ DETAILS',
  quantityRequired:'Quantity Required',
  availability:'Availability',
  datePosted:'Date Posted',
  detailedDescription:'Detailed Description',
  quoteNow:'QUOTE NOW',
  emailAlreadyExists:'Email already exists',
  enterValidEmail:"Please enter a valid email address",
  passwordCannotBeEmpty:'Password cannot be empty',
  onlyBuyersCanLoggedIn:'Only buyers can logged in.',
  enterValidName:'Please enter a valid first name',
  enterValidLastName:'Please enter a valid last name',
  enterValidContact:'Please enter a valid contact number',
  passwordLengthError:'Password cannot be less than 6 characters',
  passwordNotMatched:'Your passwords didnot matched',
  noUserRegistered:'No user registered with the email address',
  profileUpdatedSuccessfully:'Profile details updated successfully',
  passwordUpdatedSuccessfully:'Password updated successfully',
  enterValidCompanyName:'Please enter a valid company name',
  countryOrRegion:'Country/Region',
  onlySellersCanLoggedin:'Only Brown Eagle sellers can logged in.',
  fetchingLocation:'Fetching location...',
  noCategoriesFound:'No categories found',
  noSubcategoriesFound:'No sub categories found',
  addressCannotBeEmpty:'Registered address cannot be empty',
  operationalAddressCannotBeEmpty:'Operational address cannot be empty',
  websiteCannotBeEmpty:'Website cannot be empty',
  establishedCannotBeEmpty:'Company established year cannot be empty',
  employeeCountCannotBeEmpty:'Employee count cannot be empty',
  imageExceedsAlert:'You can upload upto 6 images.',
  quantity:'Quant',
  pieces:'units',
  piece:'unit',
  noRfqFound:'No RFQs found',
  subCategory:'Sub Category',
  unitPrice:'Unit Price',
  verified:'verified',
  title:'Title',
  delete:'DELETE',
  categoryTitle:'CATEGORIES',
  sendQuotationsTitle:'SEND QUOTATION',
  enterQuantity:'Enter a quantity',
  enterUnitPrice:'Enter a unit price',
  productDetail:'Product Details',
  sendProposal:'Send a Proposal',
  deliveryTime:'Delivery Time',
  enterDeliveryTime:'Enter a delivery time(in days)',
  quotationsTitle:'MY QUOTATIONS',
  searchQuotations:'Search Quotations',
  QUOTATIONS:"QUOTATIONS",
  status:'Status',
  all:'All',
  open:'Open',
  rejected:'Rejected',
  closed:'Closed',
  sortBy:'Sort By',
  startDate:'Start Date',
  endDate:'End Date',
  quotationDetalisTitle:'QUOTATION DETAILS',
  shopBy:"Shop by",
  enterTitle:'Enter a title',
  minQuantity:'Minimum Quantity',
  quotedPrice:'Quoted Price',
  estimatedDeliveryTime:'Estimated delivery time',
  enterMinQuantity:'Enter minimum quntity',
  enterEtimatedDeliveryTime:'Enter estimated delivery time',
  coverLetter:'Cover Letter',
  enterCoverLetter:'Enter a cover letter',
  pleaseEnterTitle:'Please enter a title',
  pleaseEnterMinQuantity:'Please enter a minimum quantity',
  pleaseEnterQuotedPrice:'Please enter a quoted price',
  pleaseEnterEstimatedDeliveryTime:'Please enter estimated delivery time',
  pleaseEnterCoverLetter:'Please send a cover letter',
  quottionSubmittedSuccessfully:'Your quotation has been submitted successfully',
  noQuotationsFound:'No quotations found',
  membershipPlan:'Upgrade Plan',
  membershipPlanTitle:'MEMBERSHIP PLAN',
  expandBusiness:"Let's Expand Your Business which helps you gain immediate trust from buyers",
  chooseMembershipPackage:'Choose a Membership Package',
  noPackagesAtYourLocation:'No plans at your location',
  package:'Package',
  storage:'Storage per month',
  nextRenewal:'Next Renewal',
  expireOn:'Expire on',
  unSubscribePlan:'Unsubscribe Plan',
  subscribePlan:"Subscribe Plan",
  subscribeConfirm:"Are sure want to subscribe the plan ?",
  unSubscribeConfirm:"Are sure want to unsubscribe the plan ?",
  subscriptionFailed:'Failed to Unsubscribe the plan, Please try later',
  productListing:'Total Product Listings',
  detailsTitle:'DETAILS',
  packageCost:'Package Cost',
  service:'Service',
  serviceType:'Service Type',
  serviceCost:'Service Cost',
  upgradeNow:'UPGRADE NOW',
  upload:'Upload',
  video:'Video',
  myCertificates:'My Certificates',
  myCertificatesTitle:'MY CERTIFICATES',
  noCertificatesUploaded:'No Certificates Uploaded',
  addCertificate:'ADD CERTIFICATE',
  viewCertificateTitle:'VIEW',
  clickToView:'Click to view',
  certificateTitle:'CERTIFICATE TITLE',
  somethingWentWrong:'Something went wrong. Please try again later',
  titleCannotBeEmpty:"Title cannot be empty",
  certificateUploadedSuccessfully:'Your certificate has been uploaded successfully',
  myVideosTitle:'COVER VIDEO',
  myVideos:'Cover Video',
  noVideosUploaded:'No cover video found',
  addVideo:'ADD NOW',
  canUploadOnlyOneVideo:'You can upload only 1 video',
  brownEagleWillCharge:'Brown Eagle will charge',
  commissionForThisCategory:'commission for this category',
  termsAndConditionsApplied:'Terms and Conditions Applied',
  noTermsFound:'Terms and Conditions are not applied.',
  cannotAddThisCategory:'You cannot add this category since it does not contain any sub categories yet. Please add other categories.',
  allOrders:'All',
  yearlyRfqLimit:'Yearly RFQs limit',
  contactPersonDetails:'Contact Person Details',
  name:'Name',
  contactPersonCannotBeEmpty:'Contact person details cannot be empty',
  quickDetails:'Quick Details',
  label:'Label',
  value:'Value',
  addMore:'Add More',
  pending:'pending',
  profileVerification:'Profile Verification',
  profileApproval:'Profile Approval',
  confirmed:'Confirmed Orders',
  shippedOrders:'Shipped Orders',
  deliveredOrders:'Delivered Orders',
  rejectedOrders:'Rejected Orders',
  cancelledOrders:'Cancelled Orders',
  noOrdersFound:'No orders found',
  checkout:'CHECKOUT',
  orderShippedd:'Order shipped',
  confirmedd:'Confirmed',
  cancelled:'Cancelled',
  paymentSuccessfull:'PAYMENT SUCCESSFULL',
  allOrdersTitle:'ALL ORDERS',
  from:'from',
  minOrder:'Min. Order',
  allOrders:'All',
  waitingForContractDraft:'Waiting for contract draft',
  waitingForOrderConfirmation:'Waiting for order confirmation',
  waitingForPayment:'Waiting for payment',
  waitingForPaymentConfirmation:'Waiting for payment confirmation',
  waitingForShipment:'Waiting for shipment',
  waitingForDeliveryConfirmation:'Waiting for delivery confirmation',
  orderCancelRequested:'Order cancel requested',
  disputeOrRefund:"Dispute/Refund",
  completed:'Completed',
  closed:'Closed',
  waitingForSupplier:'Waiting for supplier to confirm order',
  waitingForPayment:'Waiting for payment',
  shipped:'Shipped',
  delivered:'Delivered',
  productStatus:'Product Status',
  chat:'CHAT',
  supplierAndProductInformation:'Supplier and Product Information',
  total:'Total',
  orderDetails:'Order Details',
  orderNumber:'Order Number',
  orderSubmitted:'Order Submitted',
  cancelOrder:'CANCEL',
  track:'TRACK',
  trackOrderTitle:'TRACK ORDER',
  shippingAddress:'Shipping Address',
  landmark:'Landmark',
  buyerAndProductInformation:'Buyer and Product Information',
  reject:'REJECT',
  accept:'ACCEPT',
  rejectOrder:'REJECT ORDER',
  acceptOrder:'ACCEPT ORDER',
  orderDetailsTitle:'ORDER DETAILS',
  track:'TRACK',
  key:'Key',
  quickDetailsEx:'(ex- Color : Black)',
  customerReviews:'Customer Reviews',
  customerReview:'Customer Review',
  allReviewsTitle:'ALL REVIEWS',
  productPreview:'Product Preview',
  show:'SHOW',
  productPreviewTitle:'PRODUCT PREVIEW',
  supplierProfile:'Supplier Profile',
  view:'View',
  contactPerson:'Contact Person',
  ratingsReviews:'Ratings & Reviews',
  recentlyAddedReviews:'Recently added reviews',
  thisProductHasNoReview:'Sorry, this product has no review',
  days:'days',
  perQuantity:'per quantity',
  rfqDetails:'Rfq Details -',
  myQuotation:'My quotation',
  inDays:'in days',
  notAdded:'Not added',
  viewTermsConditions:'View Terms & Conditions',
  by:'by',
  paymentSuccessfull:'PAYMENT SUCCESSFULL',
  planUpgradedSuccessfully:'You have upgraded your plan',
  pleaseWaitPaymentMsg:'Please wait while we are processing your request...',
  activePlan:'Active Plan',
  productUsed:'Product used',
  storageUsed:'Storage used',
  storageRemaining:'Storage remaining',
  rfqUsed:'RFQ used',
  rfqRemaining:'RFQ remaining',
  noActivePlan:"You have not purchased any membership plan. Choose a Membership Package which helps you gain immediate trust from buyers",
  sellerShare:'Seller Share',
  commission:'Commission',
  productDimensions:'Product Dimensions',
  weight:'Weight(in grams)',
  width:'Width(in inches)',
  height:'Height(in inches)',
  depth:'Depth(in inches)',
  pleaseEnterDimensions:'Please add product dimensions',
  myReferences:'My References',
  noReferencesAdded:'No references added',
  addReferences:'ADD REFERENCES',
  clientInformation:'Client Information',
  shortNote:'Write a short note',
  yourReferenceCreatedSuccessfully:'Your reference has been created successfully',
  unableToOpen:'UNABLE TO OPEN',
  urlIsNotCorrect:'Url is not correct',
  yourReferenceSavedSuccessfully:'Your reference has been saved successfully',
  orderPlaced:'Your payment has been made successfully',
  shippingOrders:'Shipping orders',
  payments:'Payments',
  personalDetails:'Personal Details',
  companyDetails:'Company Details',
  kycSubmitConfirm:'Are you sure want to submit the KYC form ?',
  kycSubmittedSuccessfully:'Your KYC has been submitted successfully. You will be notified once we processed your status',
  packageDimensions: 'Package Dimensions',
  length: 'Length(in inches)',
  units: 'Units(in number)',
  shippingOptions: 'Shipping Method',
  shippingCharges: 'Shipping Charges',
  listPrice: 'List Price',
  grandTotal: 'Grand Total',
  productTermsConditions: 'Product Terms and Conditions',
  enterTermsConditions: 'Enter terms and conditions',
}
