export const fr={
  login:"S'IDENTIFIER",
  register:"REGISTRE",
  username:"Nom d'utilisateur",
  email:"Email",
  mobile:"Mobile",
  password:"Mot de passe",
  confirmPassword:"Confirmez le mot de passe",
  signup:"S'INSCRIRE",
  otpMessage:"Entrez OTP à 4 chiffres envoyé à votre mobile",
  enterOTP:"Entrez OTP",
  verify:"VÉRIFIER",
  resendOTP:"Renvoyer la vérification OTP",
  emailOrusername:"Email/Nom d'utilisateur",
  continueWithFb:"CONTINUER AVEC FACEBOOK",
  continueWithGoogle:"CONTINUER AVEC GOOGLE",
  forgotPassword:"MOT DE PASSE OUBLIÉ?",
  enterMobile:"Entrez votre numéro de portable enregistré",
  verify:"VÉRIFIER",
  trendingProducts:"PRODUITS DE TENDANCE",
  lightEquipmentTools:"OUTILS D'ÉQUIPEMENT DE LUMIÈRE",
  foodProducts:"PRODUITS ALIMENTAIRES ET DE DÉTAIL",
  latestProducts:"DERNIERS PRODUITS",
  recommendedProducts:"PRODUITS RECOMMANDÉS",
  topRatedProducts:"PRODUITS LES PLUS CLASSÉS",
  heavyEquipmentTools:"OUTILS LOURDS D'ÉQUIPEMENT",
  products:"DES PRODUITS",
  suppliers:"FOURNISSEURS",
  searchProducts:"Recherche de produits",
  searchSuppliers:"Rechercher des fournisseurs",
  recentSearches:"recherches récentes",
  popularSearches:"Recherches populaires",
  results:"résultats",
  contact:"Contact",
  productDetails:"DÉTAILS DU PRODUIT",
  companyProfile:"Profil de la société",
  follow:"SUIVRE",
  visitProfile:"VISITER LE PROFIL",
  itemDetails:"DÉTAILS DE L'ARTICLE",
  detailsPicture:"Détails Image",
  recommendedFromThisSupplier:"Recommandé par ce fournisseur",
  recommendedFromOtherSupplier:"Recommandé par un autre fournisseurs",
  sendEnquiry:"ENVOYER ENQUÊTE",
  chatNow:"DISCUTER MAINTENANT",
  sendEnquiry:"ENVOYER ENQUÊTE",
  attachPhotos:"Joindre des photos",
  recommendOtherSuppliers:"Recommander d'autres fournisseurs correspondants si ce fournisseur ne me contacte pas dans les 24 heures.",
  agreeToShareContactInfo:"J'accepte de partager mes coordonnées dans mon profil d'acheteur avec le fournisseur.",
  send:"ENVOYER",
  accounts:"COMPTES",
  manageOrders:"Gérer les commandes",
  favourites:"Favoris",
  quotations:"Vos citations",
  buyingRequest:"Demande d'achat",
  profileDetails:"Détails du profil",
  settings:"Paramètres",
  aboutUs:"À propos de nous",
  TC:"termes et conditions",
  privacyPolicy:"Politique de confidentialité",
  contactUs:"Contactez nous",
  profileDetailsTitle:"DÉTAILS DU PROFIL",
  firstName:"Prénom",
  lastName:"Nom de famille",
  contactNumber:"Numéro de contact",
  changePassword:"CHANGER LE MOT DE PASSE",
  updateDetails:"MISE À JOUR",
  otp:"OTP",
  newPassword:"nouveau mot de passe",
  save:"ENREGISTRER",
  language:"La langue",
  notifications:"Notifications",
  languageTitle:"LA LANGUE",
  companyName:"Nom de la compagnie",
  location:"Emplacement",
  logout:'CONNECTEZ - OUT',
  welcome:'Bienvenue à Brown Eagle',
  loginOrSignup:'Connectez-vous ou inscrivez-vous pour aimer, collecter et gérer les commandes',
  continueWith:'CONTINUE AVEC',
  fb:'FACEBOOK',
  google:'GOOGLE',
  enterEmail:"S'il vous plaît entrer votre adresse e-mail",
  emailSent:'Un e-mail de confirmation a été envoyé à votre boîte aux lettres',
  checkEmail:'Merci de consulter vos emails',
  resendEmail:"Ré-envoyer l'email",
  notReceiveEmail:'Avoir un problème à recevoir un courriel',
  clickHere:'Cliquez ici',
  manageProducts:'Gérer les produits',
  manageProductsTitle:'Gérer les produits',
  manageBusiness:'Gérer les affaires',
  allProducts:'Tous les produits',
  approvedProducts:'Produits approuvés',
  approvalPending:"En attente d'approbation",
  approvedProductsTitle:'Produits approuvés',
  rejectedProducts:'Produits rejetés',
  rejectedProductsTitle:'Produits rejetés',
  addNewProduct:'AJOUTER UN NOUVEAU PRODUIT',
  allProductsTitle:'TOUS LES PRODUITS',
  productNameCannotEmpty:'Le nom du produit ne peut pas être vide',
  ok:"D'accord",
  pleaseEnterKeyword:'Veuillez entrer au moins un mot-clé de produit',
  productCatCannotEmpty:'La catégorie de produit ne peut pas être vide',
  productSubCatCannotEmpty:'La sous-catégorie de produits ne peut pas être vide',
  addProductDescription:'Ajouter une description du produit',
  productQualityCannotBeEmpty:'La quantité minimale du produit ne peut pas être vide',
  addProductPrice:'Ajouter un prix du produit',
  basicInformation:'Informations de base',
  productName:'Nom du produit',
  productKeywords:'Mots clés du produit',
  catInformation:'Informations sur la catégorie',
  category:'Catégorie',
  searchCat:'Rechercher des catégories',
  subCat:'Sous-catégorie',
  productDetailsInformation:'Informations sur le produit',
  productPhoto:'Photo de produit / vidéo',
  productDescription:'Description du produit',
  requirement:'Exigence',
  minQuality:'Quantité minimum (ex - 10)',
  productPrice:'Prix du produit',
  submit:'SOUMETTRE',
  addProductTitle:'AJOUTER UN PRODUIT',
  cancel:'Annuler',
  fromCamera:'De la caméra',
  fromLibrary:'De la bibliothèque',
  apparel:'Vêtements, textiles et accessoires',
  transportation:'Auto et transport',
  electronics:'Électronique',
  machinery:'Machines, matériel et outils',
  gifts:'Cadeaux, sports et passe-temps',
  homeLights:'Maison, Lumières et Construction',
  healthBeauty:'Santé & Beauté',
  jewelryBags:'Bijoux, sacs et chaussures',
  electricalEquipment:'Équipement électrique',
  agriculture:'Agriculture et Alimentation',
  packaging:'Emballage, publicité et bureau',
  rawProcessing:'Matières brutes et transformées',
  Apparel:'Vêtements',
  textile:'Textile et produits en cuir',
  fashion:'Accessoires de mode',
  automobiles:'Automobiles et motos',
  Transportation:'Transport',
  computer:'Des ordinateurs',
  consumerElectronics:'Électronique grand public',
  homeAppliances:'Appareils ménagers',
  security:'Protection de la sécurité',
  hardware:'Outils matériels',
  instruments:"Instruments de mesure et d'analyse",
  Machinery:'Machinerie',
  mechanicalParts:'Pièces mécaniques et service de fabrication',
  giftsCrafts:'Cadeaux et artisanat',
  sportsEnternainment:'Sports et divertissements',
  toys:'Jouets et passe-temps',
  construction:'Construction et immobilier',
  lights:'Lumières et éclairage',
  homeGarden:'Maison et jardin',
  furniture:'meubles',
  healthMedical:'Santé et médecine',
  beautyCare:'Beauté et soins personnels',
  luggageBags:'Bagages, sacs et étuis',
  timePieces:'Montres, bijoux, lunettes',
  shoesAccessories:'Chaussures et accessoires',
  electricalSuppliers:'Matériel électrique et fournitures',
  elctronicComponents:'Composants électroniques et fournitures',
  telecommunications:'télécommunications',
  agriculture:'Agriculture',
  foodBeverage:'Aliments et Boissons',
  packagingPrinting:'Emballage et impression',
  schoolSuppliers:'Bureau et fournitures scolaires',
  serviceEquipment:'Équipement de service',
  mineralsMetallurgy:'Minéraux et métallurgie',
  chemicals:'Chemicals',
  rubberPlastic:'Caoutchouc et plastiques',
  energy:'énergie',
  environment:'environnement',
  youHaveNotAddedProduct:"Vous n'avez encore ajouté aucun produit.",
  pendingProducts:'PRODUITS EN ATTENTE',
  areYouSure:'Êtes-vous sûr?',
  yes:'Oui',
  update:'METTRE À JOUR',
  notApproved:"Aucun de vos produits n'a été approuvé",
  noProductsFound:'Aucun produit trouvé',
  clickToEdit:'Cliquez pour éditer',
  haveAnyQues:'Si vous avez des questions concernant ces conditions, veuillez nous contacter.',
  contact:'CONTACT',
  address:'BROWN EAGLE INC.\n1000 N West Street\nSuite 1200\nWilmington, DE 19801\nNuméro de téléphone: 302-295-3816\nNuméro de fax: 302-295-4801',
  registeredAddress:'Adresse enregistrée',
  Address:'Adresse',
  city:'Ville',
  state:'Etat',
  zipCode:'Code postal',
  country:'Pays',
  operationalAddress:'Adresse opérationnelle',
  companyInfo:'Informations sur la société',
  website:'Site web(ex: http://www.example.com)',
  established:'Établi',
  employeeCount:"Nombre d'employés",
  description:"Description de l'entreprise",
  emailNotVerified:'E-mail non-vérifié',
  verifyNow:'Cliquez sur VERIFY pour vérifier votre compte BrownEagle',
  later:'Plus tard',
  mainProducts:'Principaux produits',
  add:'AJOUTER',
  keywordsEx:'(Par exemple: Keyword1, Keyword2, Keyword3)',
  settingsTitle:'PARAMÈTRES',
  TCTtile:'TERMES ET CONDITIONS',
  contactUsTitle:'CONTACTEZ NOUS',
  profileNotVerified:'VERIFICATION DE PROFIL EN ATTENTE',
  ok:"D'accord",
  sameAsRegisteredAddress:"Identique à l'adresse enregistrée",
  passwordResetMsg:'Pour réinitialiser votre mot de passe, un e-mail a été envoyé à votre boîte aux lettres',
  account:'Compte',
  payment:'Paiement',
  sales:'Ventes',
  support:'Soutien',
  others:'Autres',
  chooseDepartment:'Choisissez le département',
  message:'Message...',
  rfqTitle:"Demande d'achat",
  searchRfq:'Recherche RFQ',
  rfqDetailsTitle:'DÉTAILS DE LA RFQ',
  quantityRequired:'Quantité requise',
  availability:'Disponibilité',
  datePosted:'Date publiée',
  detailedDescription:'Description détaillée',
  quoteNow:'DEVIS MAINTENANT',
  emailAlreadyExists:"Email existe déjà",
  enterValidEmail:"Veuillez entrer une adresse e-mail valide",
  passwordCannotBeEmpty:'Le mot de passe ne peut pas être vide',
  onlyBuyersCanLoggedIn:'Seuls les acheteurs peuvent se connecter.',
  enterValidName:'Veuillez entrer un prénom valide',
  enterValidLastName:'Veuillez entrer un nom de famille valide',
  enterValidContact:'Veuillez entrer un numéro de contact valide',
  passwordLengthError:'Le mot de passe ne peut pas être inférieur à 6 caractères',
  passwordNotMatched:'Vos mots de passe ne correspondent pas',
  noUserRegistered:"Aucun utilisateur enregistré avec l'adresse e-mail",
  profileUpdatedSuccessfully:'Détails du profil mis à jour avec succès',
  passwordUpdatedSuccessfully:'Mot de passe mis à jour',
  enterValidCompanyName:"Veuillez entrer un nom d'entreprise valide",
  countryOrRegion:'Pays/Région',
  onlySellersCanLoggedin:'Seuls les vendeurs de Brown Eagle peuvent se connecter.',
  fetchingLocation:"Récupérer l'emplacement ...",
  noCategoriesFound:'Aucune catégorie trouvée',
  noSubcategoriesFound:'Aucune sous-catégorie trouvée',
  addressCannotBeEmpty:"L'adresse ne peut pas être vide",
  operationalAddressCannotBeEmpty:"L'adresse opérationnelle ne peut pas être vide",
  websiteCannotBeEmpty:'Le site ne peut pas être vide',
  establishedCannotBeEmpty:"L'année établie par la société ne peut pas être vide",
  employeeCountCannotBeEmpty:"Le nombre d'employés ne peut pas être vide",
  imageExceedsAlert:"Vous pouvez télécharger jusqu'à 6 images.",
  quantity:'Quantité',
  pieces:'unités',
  piece:'unité',
  noRfqFound:'Aucun RFQs trouvé',
  subCategory:'Sous-catégorie',
  unitPrice:'Prix unitaire',
  verified:'vérifié',
  title:'Titre',
  delete:'SUPPRIMER',
  categoryTitle:'CATÉGORIES',
  sendQuotationsTitle:'ENVOYER DES COTATION',
  enterQuantity:'Entrez une quantité',
  enterUnitPrice:'Entrez un prix unitaire',
  productDetail:'Détails du produit',
  sendProposal:'Envoyer une proposition',
  deliveryTime:'Délai de livraison',
  enterDeliveryTime:'Entrez un délai de livraison (en jours)',
  quotationsTitle:'MES DEVIS',
  searchQuotations:'Rechercher des citations',
  QUOTATIONS:"CITATIONS",
  status:'Statut',
  all:'Tout',
  open:'ouvert',
  rejected:'rejeté',
  closed:'Fermé',
  sortBy:'Trier par',
  startDate:'Date de début',
  endDate:'Date de fin',
  quotationDetalisTitle:'DÉTAILS DE DEVIS',
  shopBy:"Acheter par",
  enterTitle:'Entrez un titre',
  minQuantity:'Quantité minimum',
  quotedPrice:'Prix indiqué',
  estimatedDeliveryTime:'Délai de livraison estimé',
  enterMinQuantity:'Entrer la quantité minimum',
  enterEtimatedDeliveryTime:'Entrer le délai de livraison estimé',
  coverLetter:"Lettre d'accompagnement",
  enterCoverLetter:'Entrez une lettre de motivation',
  pleaseEnterTitle:"S'il vous plaît entrer un titre",
  pleaseEnterMinQuantity:'Veuillez entrer une quantité minimum',
  pleaseEnterQuotedPrice:"S'il vous plaît entrer un prix",
  pleaseEnterEstimatedDeliveryTime:'Veuillez entrer le délai de livraison estimé',
  pleaseEnterCoverLetter:"Merci d'envoyer une lettre de motivation",
  quottionSubmittedSuccessfully:'Votre devis a été classé avec succès',
  noQuotationsFound:'Aucune citation trouvée',
  membershipPlan:"Plan de mise à niveau",
  membershipPlanTitle:"PLAN D'ADHÉSION",
  expandBusiness:"Faisons Développez votre entreprise ce qui vous aide à gagner la confiance immédiate des acheteurs",
  chooseMembershipPackage:"Choisissez un forfait d'adhésion",
  noPackagesAtYourLocation:'Aucun plan à votre emplacement',
  package:'Paquet',
  storage:'Stockage par mois',
  nextRenewal:'Prochain renouvellement',
  unSubscribePlan:"Plan de désabonnement",
  subscribePlan:"Plan d'abonnement",
  subscribeConfirm:"Êtes-vous sûr de vouloir souscrire au plan?",
  unSubscribeConfirm:"Voulez-vous vraiment vous désabonner du plan?",
  subscriptionFailed:'Échec de la désinscription du plan, veuillez réessayer plus tard',
  expireOn:'Expire le',
  productListing:'Nombre total de produits',
  detailsTitle:'DÉTAILS',
  packageCost:'Coût du paquet',
  service:'Service',
  serviceType:'Type de service',
  serviceCost:'Coût du service',
  upgradeNow:'MISE À JOUR MAINTENANT',
  upload:'Télécharger',
  video:'vidéo',
  myCertificates:'Mes certificats',
  myCertificatesTitle:'MES CERTIFICATS',
  noCertificatesUploaded:'Aucun certificat téléchargé',
  addCertificate:'AJOUTER UN CERTIFICAT',
  viewCertificateTitle:'VUE',
  clickToView:'Cliquez pour voir',
  certificateTitle:'TITRE DU CERTIFICAT',
  somethingWentWrong:"Quelque chose s'est mal passé. Veuillez réessayer plus tard",
  titleCannotBeEmpty:"Le titre ne peut pas être vide",
  certificateUploadedSuccessfully:'Votre certificat a été téléchargé avec succès',
  myVideosTitle:'COUVRIR LA VIDEO',
  myVideos:'Couverture vidéo',
  noVideosUploaded:'Aucune vidéo de couverture trouvée',
  addVideo:'Ajouter maintenant',
  canUploadOnlyOneVideo:"Vous ne pouvez télécharger qu'une seule vidéo",
  brownEagleWillCharge:'Brown Eagle chargera',
  commissionForThisCategory:'commission pour cette catégorie',
  termsAndConditionsApplied:'Termes et conditions appliqués',
  noTermsFound:'Les termes et conditions ne sont pas appliqués.',
  cannotAddThisCategory:"Vous ne pouvez pas ajouter cette catégorie car elle ne contient pas encore de sous-catégories. S'il vous plaît ajouter d'autres catégories.",
  allOrders:'Tout',
  yearlyRfqLimit:'Limite annuelle des RFQ',
  contactPersonDetails:'Détails de la personne de contact',
  name:'prénom',
  contactPersonCannotBeEmpty:'Les coordonnées du contact ne peuvent être vides',
  quickDetails:'Détails rapides',
  label:'Étiquette',
  value:'Valeur',
  addMore:'Ajouter plus',
  pending:'en attendant',
  profileVerification:'Vérification du profil',
  profileApproval:'Approbation du profil',
  confirmed:'Commandes confirmées',
  shippedOrders:'Commandes expédiées',
  deliveredOrders:'Commandes livrées',
  rejectedOrders:'Ordres rejetés',
  cancelledOrders:'Commandes annulées',
  noOrdersFound:'Aucune commande trouvée',
  checkout:'CHECK-OUT',
  orderShippedd:'Commande expédiée',
  confirmedd:'Confirmé',
  cancelled:'Annulé',
  paymentSuccessfull:'Paiement réussi',
  allOrdersTitle:'TOUTES LES COMMANDES',
  from:'de',
  minOrder:'Commande minimum',
  allOrders:'Tout',
  waitingForContractDraft:"En attente d'un projet de contrat",
  waitingForOrderConfirmation:'En attente de confirmation de commande',
  waitingForPayment:'En attente de paiement',
  waitingForPaymentConfirmation:'En attente de confirmation de paiement',
  waitingForShipment:"En attente d'expédition",
  waitingForDeliveryConfirmation:'En attente de confirmation de livraison',
  orderCancelRequested:'Commande annuler demandée',
  disputeOrRefund:"Dispute/remboursement",
  completed:'terminé',
  closed:'Fermé',
  waitingForSupplier:'En attente de confirmation de commande par le fournisseur',
  waitingForPayment:'en attente de paiement',
  shipped:'Expédié',
  delivered:'Livré',
  productStatus:'État du produit',
  chat:'BAVARDER',
  supplierAndProductInformation:'Informations sur le fournisseur et le produit',
  total:'Total',
  orderDetails:'détails de la commande',
  orderNumber:'Numéro de commande',
  orderSubmitted:'Commande soumise',
  cancelOrder:'ANNULER',
  track:'PISTE',
  trackOrderTitle:'SUIVI DE COMMANDE',
  shippingAddress:'Adresse de livraison',
  landmark:'Point de repère',
  buyerAndProductInformation:"nformations sur l'acheteur et le produit",
  reject:'REJETER',
  accept:'ACCEPTEZ',
  rejectOrder:"REJETER L'ORDRE",
  acceptOrder:'ACCEPTER LA COMMANDE',
  orderDetailsTitle:'DÉTAILS DE LA COMMANDE',
  track:'TRACK',
  key:'clé',
  quickDetailsEx:'(ex-couleur: noir)',
  customerReviews:'Avis des clients',
  customerReview:'Avis des clients',
  allReviewsTitle:'TOUS LES AVIS',
  productPreview:'Aperçu du produit',
  show:'MONTRER',
  productPreviewTitle:'APERÇU DU PRODUIT',
  supplierProfile:'Profil du fournisseur',
  view:'Vue',
  contactPerson:'Contact La personne',
  ratingsReviews:'Notes et avis',
  recentlyAddedReviews:'Critiques récemment ajoutées',
  thisProductHasNoReview:"Désolé, ce produit n'a pas d'avis",
  days:'journées',
  perQuantity:'par quantité',
  rfqDetails:'Rfq Détails -',
  myQuotation:'Mon devis',
  inDays:'en jours',
  notAdded:'Non ajouté',
  viewTermsConditions:'Afficher les conditions générales',
  by:'par',
  paymentSuccessfull:'Paiement réussi',
  planUpgradedSuccessfully:'Vous avez mis à jour votre plan',
  pleaseWaitPaymentMsg:'Veuillez patienter pendant que nous traitons votre demande ...',
  activePlan:'Plan actif',
  productUsed:'Produit utilisé',
  storageUsed:'Stockage utilisé',
  storageRemaining:'Stockage restant',
  rfqUsed:'RFQ utilisé',
  rfqRemaining:'RFQ restant',
  noActivePlan:"Vous n'avez pas acheté de plan d'adhésion. Choisissez un forfait d'adhésion qui vous aide à gagner la confiance immédiate des acheteurs",
  sellerShare:'Vendeur Partager',
  commission:'Commission',
  productDimensions:'Dimensions du produit',
  weight:'Poids(en grammes)',
  width:'Largeur(en pouces)',
  height:'Hauteur(en pouces)',
  depth:'Profondeur(en pouces)',
  pleaseEnterDimensions:'Veuillez ajouter les dimensions du produit',
  myReferences:'Mes références',
  noReferencesAdded:'Aucune référence ajoutée',
  addReferences:'AJOUTEZ DES RÉFÉRENCES',
  clientInformation:'Information du client',
  shortNote:'Ecrire une courte note',
  yourReferenceCreatedSuccessfully:'Votre référence a été créée avec succès',
  unableToOpen:"INCAPABLE D'OUVRIR",
  urlIsNotCorrect:"Url n'est pas correct",
  yourReferenceSavedSuccessfully:'Votre référence a été enregistrée avec succès',
  orderPlaced:'Votre paiement a été effectué avec succès',
  shippingOrders:"Commandes d'expédition",
  payments:'Paiements',
  personalDetails:'Détails personnels',
  companyDetails:'Détails de la société',
  kycSubmitConfirm:'Voulez-vous vraiment soumettre le formulaire KYC?',
  kycSubmittedSuccessfully:'Votre KYC a été soumis avec succès. Vous serez averti dès que nous aurons traité votre statut',
  packageDimensions: 'Dimensions du colis',
  length: 'Longueur(en pouces)',
  units: 'Units(in number)',
  shippingOptions: "Méthode d'expédition",
  shippingCharges: "Frais d'expédition",
  listPrice: 'Prix catalogue',
  grandTotal: 'Total général',
  productTermsConditions: 'Conditions générales du produit',
  enterTermsConditions: 'Entrez les termes et conditions',

}
