export const de={
  login:"ANMELDUNG",
  register:"REGISTRIEREN",
  username:"Nutzername",
  email:"Email",
  mobile:"Handy, Mobiltelefon",
  password:"Passwort",
  confirmPassword:"Bestätige das Passwort",
  signup:"ANMELDEN",
  otpMessage:"Geben Sie 4-stelliges OTP an Ihr Mobiltelefon ein",
  enterOTP:"Geben Sie OTP ein",
  verify:"ÜBERPRÜFEN",
  resendOTP:"Erneutes Senden der Überprüfungs-OTP",
  emailOrusername:"E-Mail/Benutzername",
  continueWithFb:"WEITER MIT FACEBOOK",
  continueWithGoogle:"WEITER MIT GOOGLE",
  forgotPassword:"PASSWORT VERGESSEN?",
  enterMobile:"Geben Sie Ihre registrierte Handynummer ein",
  verify:"ÜBERPRÜFEN",
  trendingProducts:"TOP TRENDING PRODUKTE",
  lightEquipmentTools:"LICHTAUSRÜSTUNGSWERKZEUGE",
  foodProducts:"Lebensmittel und Einzelhandel",
  latestProducts:"NEUESTE PRODUKTE",
  recommendedProducts:"EMPFOHLENE PRODUKTE",
  topRatedProducts:"TOP BEZAHLTE PRODUKTE",
  heavyEquipmentTools:"SCHWERE GERÄTEWERKZEUGE",
  products:"PRODUKTE",
  suppliers:"LIEFERANTEN",
  searchProducts:"Produktsuche",
  searchSuppliers:"Suche Lieferanten",
  recentSearches:"Letzte Suchanfragen",
  popularSearches:"beliebte Suchanfragen",
  results:"Ergebnisse",
  contact:"Kontakt",
  productDetails:"PRODUKTDETAILS",
  companyProfile:"Firmenprofil",
  follow:"FOLGEN",
  visitProfile:"BESUCH PROFIL",
  itemDetails:"ARTIKELDETAILS",
  detailsPicture:"Details Bild",
  recommendedFromThisSupplier:"Empfohlen von diesem Lieferanten",
  recommendedFromOtherSupplier:"Von anderen Lieferanten empfohlen",
  sendEnquiry:"ANFRAGE ABSENDEN",
  chatNow:"CHAT JETZT",
  sendEnquiry:"ANFRAGE ABSENDEN",
  attachPhotos:"Fotos anfügen",
  recommendOtherSuppliers:"Empfehlen Sie andere passende Lieferanten, wenn dieser Lieferant mich nicht innerhalb von 24 Stunden kontaktiert.",
  agreeToShareContactInfo:"Ich stimme zu, meine Kontaktinformationen in meinem Käuferprofil mit dem Lieferanten zu teilen.",
  send:"SENDEN",
  accounts:"KONTEN",
  manageOrders:"Bestellungen verwalten",
  favourites:"Favoriten",
  quotations:"Ihre Angebote",
  buyingRequest:"Kaufanfrage",
  profileDetails:"Profildetails",
  settings:"die Einstellungen",
  aboutUs:"Über uns",
  TC:"Geschäftsbedingungen",
  privacyPolicy:"Datenschutz-Bestimmungen",
  contactUs:"Kontaktiere uns",
  profileDetailsTitle:"PROFILDETAILS",
  firstName:"Vorname",
  lastName:"Familienname, Nachname",
  contactNumber:"Kontakt Nummer",
  changePassword:"PASSWORT ÄNDERN",
  updateDetails:"UPDATE DETAILS",
  otp:"OTP",
  newPassword:"Neues Kennwort",
  save:"SPAREN",
  language:"Sprache",
  notifications:"Benachrichtigungen",
  languageTitle:"SPRACHE",
  companyName:"Name der Firma",
  location:"Ort",
  logout:'AUSLOGGEN',
  welcome:'Willkommen bei Brauner Adler',
  loginOrSignup:'Einloggen oder registrieren, um Bestellungen zu sammeln, zu verwalten und zu verwalten',
  continueWith:'WEITERMACHEN MIT',
  fb:'FACEBOOK',
  google:'GOOGLE',
  enterEmail:'Geben Sie bitte Ihre Email-Adresse ein',
  emailSent:'Eine Bestätigungs-E-Mail wurde an Ihre Mailbox gesendet',
  checkEmail:'Bitte überprüfen Sie Ihre E-Mail',
  resendEmail:'E-Mail zurücksenden',
  notReceiveEmail:'Problem beim Empfangen von E-Mails',
  clickHere:'Klick hier',
  manageProducts:'Produkte verwalten',
  manageProductsTitle:'Produkte verwalten',
  manageBusiness:'Geschäft verwalten',
  allProducts:'Alle Produkte',
  approvedProducts:'Zugelassene Produkte',
  approvalPending:'Bestätigung ausstehend',
  rejectedProducts:'Abgelehnte Produkte',
  approvedProductsTitle:'Zugelassene Produkte',
  rejectedProductsTitle:'Abgelehnte Produkte',
  addNewProduct:'Füge ein neues Produkt hinzu',
  allProductsTitle:'ALLE PRODUKTE',
  productNameCannotEmpty:'Der Produktname darf nicht leer sein',
  ok:'OK',
  pleaseEnterKeyword:'Bitte geben Sie mindestens ein Product Keyword ein',
  productCatCannotEmpty:'Produktkategorie darf nicht leer sein',
  productSubCatCannotEmpty:'Die Produktunterkategorie darf nicht leer sein',
  addProductDescription:'Fügen Sie eine Produktbeschreibung hinzu',
  productQualityCannotBeEmpty:'Die Produktminimalmenge darf nicht leer sein',
  addProductPrice:'Fügen Sie einen Produktpreis hinzu',
  basicInformation:'Grundinformation',
  productName:'Produktname',
  productKeywords:'Produkt Schlüsselwörter',
  catInformation:'Kategorieinformationen',
  category:'Kategorie',
  searchCat:'Suchkategorien',
  subCat:'Unterkategorie',
  productDetailsInformation:'Produktdetails Informationen',
  productPhoto:'Produkt Foto / Video',
  productDescription:'Produktbeschreibung',
  requirement:'Anforderung',
  minQuality:'Mindestmenge (ex - 10)',
  productPrice:'Produktpreis',
  submit:'EINREICHEN',
  addProductTitle:'PRODUKT HINZUFÜGEN',
  cancel:'Stornieren',
  fromCamera:'Von der Kamera',
  fromLibrary:'Aus der Bibliothek',
  apparel:'Bekleidung, Textilien und Accessoires',
  transportation:'Auto & Transportat',
  electronics:'Elektronik',
  machinery:'Maschinen, Hardware und Werkzeuge',
  gifts:'Geschenke, Sport & Hobbies',
  homeLights:'Zuhause, Licht & Konstruktion',
  healthBeauty:'Gesundheit & Schönheit',
  jewelryBags:'Schmuck, Taschen und Schuhe',
  electricalEquipment:'Elektrische Ausrüstung',
  agriculture:'Landwirtschaft und Nahrung',
  packaging:'Verpackung, Werbung und Büro',
  rawProcessing:'Rohe und verarbeitete Materialien',
  Apparel:'Bekleidung',
  textile:'Textil- und Lederwaren',
  fashion:'Mode-Accessoires',
  automobiles:'Autos & Motorräder',
  Transportation:'Transport',
  computer:'Computers',
  consumerElectronics:'Unterhaltungselektronik',
  homeAppliances:'Haushaltsgeräte',
  security:'Sicherheitsschutz',
  hardware:'Mechanische Werkzeuge',
  instruments:'Mess- und Analysegeräte',
  Machinery:'Maschinen',
  mechanicalParts:'Mechanischer Teil und Herstellungsservice',
  giftsCrafts:'Geschenke und Kunsthandwerk',
  sportsEnternainment:'Sport und Unterhaltung',
  toys:'Spielzeuge und Hobbys',
  construction:'Bau & Immobilien',
  lights:'Lichter und Beleuchtung',
  homeGarden:'Haus & Garten',
  furniture:'Möbel',
  healthMedical:'Gesundheit und Medizin',
  beautyCare:'Schönheit und Körperpflege',
  luggageBags:'Gepäck, Taschen und Koffer',
  timePieces:'Uhren, Schmuck, Brillen',
  shoesAccessories:'Schuhe & Accessoires',
  electricalSuppliers:'Elektrische Ausrüstung und Zubehör',
  elctronicComponents:'Elektronische Komponenten und Zubehör',
  telecommunications:'Telekommunikation',
  agriculture:'Landwirtschaft',
  foodBeverage:'Essen und Trinken',
  packagingPrinting:'Verpackung und Druck',
  schoolSuppliers:'Büro & Schulbedarf',
  serviceEquipment:'Serviceausrüstung',
  mineralsMetallurgy:'Mineralien & Metallurgie',
  chemicals:'Chemicals',
  rubberPlastic:'Gummi und Kunststoffe',
  energy:'Energie',
  environment:'Umwelt',
  youHaveNotAddedProduct:'Sie haben noch kein Produkt hinzugefügt.',
  pendingProducts:'Anstehende Produkte',
  areYouSure:'Bist du sicher?',
  yes:'Ja',
  update:'AKTUALISIEREN',
  notApproved:'Keines Ihrer Produkte wurde genehmigt',
  noProductsFound:'Keine Produkte gefunden',
  clickToEdit:'Zum Bearbeiten anklicken',
  haveAnyQues:'Wenn Sie Fragen zu diesen Bedingungen haben, kontaktieren Sie uns bitte.',
  contact:'KONTAKT',
  address:'BROWN EAGLE INC.\n1000 N West Street\nSuite 1200\nWilmington, DE 19801\nTelefonnummer: 302-295-3816\nFaxnummer: 302-295-4801',
  registeredAddress:'Registrierte Adresse',
  Address:'Adresse',
  city:'Stadt',
  state:'Staat',
  zipCode:'Postleitzahl',
  country:'Land',
  operationalAddress:'Betriebsadresse',
  companyInfo:'Unternehmensinformationen',
  website:'Website(ex: http://www.example.com)',
  established:'Etabliert',
  employeeCount:'Mitarbeiterzahl',
  description:'Firmenbeschreibung',
  emailNotVerified:'E-MAIL NICHT VERIFIZIERT',
  verifyNow:'Klicken Sie auf VERIFY, um Ihr BrownEagle-Konto zu bestätigen',
  later:'Später',
  mainProducts:'Hauptprodukte',
  add:'HINZUFÜGEN',
  keywordsEx:'(zB: Schlüsselwort1, Schlüsselwort2, Schlüsselwort3)',
  settingsTitle:'DIE EINSTELLUNGEN',
  TCTtile:'TERMS & BEDINGUNGEN',
  contactUsTitle:'KONTAKTIERE UNS',
  profileNotVerified:'PROFIL ÜBERPRÜFUNG PENDING',
  ok:'OK',
  sameAsRegisteredAddress:'Wie registrierte Adresse',
  passwordResetMsg:'Um Ihr Passwort zurückzusetzen, wurde eine E-Mail an Ihr Postfach gesendet',
  account:'Konto',
  payment:'Zahlung',
  sales:'Der Umsatz',
  support:'Unterstützung',
  others:'Andere',
  chooseDepartment:'Wählen Sie Abteilung',
  message:'Botschaft...',
  rfqTitle:'KAUFANFRAGE',
  searchRfq:'Suche RFQ',
  rfqDetailsTitle:'Angebotsdetails',
  quantityRequired:'Benötigte Menge',
  availability:'Verfügbarkeit',
  datePosted:'Veröffentlichungsdatum',
  detailedDescription:'Ausführliche Beschreibung',
  quoteNow:'Zitieren Sie jetzt',
  emailAlreadyExists:'E-Mail existiert bereits',
  enterValidEmail:"Bitte geben Sie eine gültige E-Mail-Adresse ein",
  passwordCannotBeEmpty:'Das Passwort darf nicht leer sein',
  onlyBuyersCanLoggedIn:'Nur Käufer können sich anmelden.',
  enterValidName:'Bitte geben Sie einen gültigen Vornamen ein',
  enterValidLastName:'Bitte geben Sie einen gültigen Nachnamen ein',
  enterValidContact:'Bitte geben Sie eine gültige Telefonnummer ein',
  passwordLengthError:'Das Passwort darf nicht weniger als 6 Zeichen lang sein',
  passwordNotMatched:'Ihre Passwörter stimmen nicht überein',
  noUserRegistered:'Kein Benutzer mit der E-Mail-Adresse registriert',
  profileUpdatedSuccessfully:'Profildetails wurden erfolgreich aktualisiert',
  passwordUpdatedSuccessfully:'Passwort wurde erfolgreich aktualisiert',
  enterValidCompanyName:'Bitte geben Sie einen gültigen Firmennamen ein',
  countryOrRegion:'Land/Region',
  onlySellersCanLoggedin:'Nur Brown Eagle Verkäufer können eingeloggt sein.',
  fetchingLocation:'Mietung abholen ...',
  noCategoriesFound:'Keine Kategorien gefunden',
  noSubcategoriesFound:'Keine Unterkategorien gefunden',
  addressCannotBeEmpty:'Die Adresse darf nicht leer sein',
  operationalAddressCannotBeEmpty:'Die Betriebsadresse darf nicht leer sein',
  websiteCannotBeEmpty:'Die Website darf nicht leer sein',
  establishedCannotBeEmpty:'Firmengründungsjahr darf nicht leer sein',
  employeeCountCannotBeEmpty:'Mitarbeiteranzahl darf nicht leer sein',
  imageExceedsAlert:'Sie können bis zu 6 Bilder hochladen.',
  quantity:'Inventar',
  pieces:'Einheiten',
  piece:'Einheit',
  noRfqFound:'Keine RFQs gefunden',
  subCategory:'Unterkategorie',
  unitPrice:'Einzelpreis',
  verified:'verifiziert',
  title:'Titel',
  delete:'LÖSCHEN',
  categoryTitle:'KATEGORIEN',
  sendQuotationsTitle:'SENDEN SIE ZITAT',
  enterQuantity:'Geben Sie eine Menge ein',
  enterUnitPrice:'Geben Sie einen Stückpreis ein',
  productDetail:'Produktdetails',
  sendProposal:'Senden Sie einen Vorschlag',
  deliveryTime:'Lieferzeit',
  enterDeliveryTime:'Geben Sie eine Lieferzeit (in Tagen) ein',
  quotationsTitle:'Meine Angebote',
  searchQuotations:'Zitate suchen',
  QUOTATIONS:"ZITATE",
  status:'Status',
  all:'alle',
  open:'geöffnet',
  rejected:'zurückgewiesen',
  closed:'Geschlossen',
  sortBy:'Sortieren nach',
  startDate:'Startdatum',
  endDate:'Enddatum',
  quotationDetalisTitle:'ZAHLUNGSDETAILS',
  shopBy:"Einkaufen bei",
  enterTitle:'Gib einen Titel ein',
  minQuantity:'Mindestmenge',
  quotedPrice:'Angebotspreis',
  estimatedDeliveryTime:'Voraussichtliche Lieferzeit',
  enterMinQuantity:'Geben Sie die Mindestmenge ein',
  enterEtimatedDeliveryTime:'Geben Sie die voraussichtliche Lieferzeit ein',
  coverLetter:'Anschreiben',
  enterCoverLetter:'Geben Sie ein Anschreiben ein',
  pleaseEnterTitle:'Bitte geben Sie einen Titel ein',
  pleaseEnterMinQuantity:'Bitte geben Sie eine Mindestmenge ein',
  pleaseEnterQuotedPrice:'Bitte geben Sie einen Angebotspreis ein',
  pleaseEnterEstimatedDeliveryTime:'Bitte geben Sie die voraussichtliche Lieferzeit ein',
  pleaseEnterCoverLetter:'Bitte senden Sie ein Anschreiben',
  quottionSubmittedSuccessfully:'Ihr Angebot wurde erfolgreich eingereicht',
  noQuotationsFound:'Keine Angebote gefunden',
  membershipPlan:'Upgrade-Plan',
  membershipPlanTitle:'MITGLIEDSCHAFT PLAN',
  expandBusiness:"lassen Sie uns Erweitern Sie Ihr Geschäft das hilft Ihnen, sofortiges Vertrauen von Käufern zu gewinnen",
  chooseMembershipPackage:'Wählen Sie ein Mitgliedschaftspaket',
  noPackagesAtYourLocation:'Keine Pläne an deinem Standort',
  package:'Paket',
  storage:'Lagerung pro Monat',
  nextRenewal:'Nächste Erneuerung',
  unSubscribePlan:"Abo kündigen",
  subscribePlan:'Abonnieren Sie den Plan',
  subscribeConfirm:"Möchten Sie den Plan wirklich abonnieren?",
  unSubscribeConfirm:"Möchten Sie den Plan wirklich abbestellen?",
  subscriptionFailed:'Der Plan konnte nicht abbestellt werden. Bitte versuchen Sie es später erneut',
  expireOn:'Läuft ab am',
  productListing:'Gesamtprodukteinträge',
  detailsTitle:'DETAILS',
  packageCost:'Paketkosten',
  service:'Service',
  serviceType:'Servicetyp',
  serviceCost:'Servicekosten',
  upgradeNow:'AKTUALISIEREN',
  upload:'hochladen',
  video:'Video',
  myCertificates:'Meine Zertifikate',
  myCertificatesTitle:'MEINE ZERTIFIKATE',
  noCertificatesUploaded:'Keine Zertifikate hochgeladen',
  addCertificate:'ZERTIFIKAT HINZUFÜGEN',
  viewCertificateTitle:'VIEW',
  clickToView:'Klicken Sie, um zu sehen',
  certificateTitle:'ZERTIFIKAT TITEL',
  somethingWentWrong:'Etwas ist schief gelaufen. Bitte versuche es später erneut',
  titleCannotBeEmpty:"Der Titel darf nicht leer sein",
  certificateUploadedSuccessfully:'Ihr Zertifikat wurde erfolgreich hochgeladen',
  myVideosTitle:'VIDEO ABDECKEN',
  myVideos:'Videoabdeckung',
  noVideosUploaded:'Kein Cover-Video gefunden',
  addVideo:'Jetzt hinzufügen',
  canUploadOnlyOneVideo:'Du kannst nur 1 Video hochladen',
  brownEagleWillCharge:'Brown Eagle wird geladen',
  commissionForThisCategory:'kommission für diese Kategorie',
  termsAndConditionsApplied:'Allgemeine Geschäftsbedingungen',
  noTermsFound:'Allgemeine Geschäftsbedingungen werden nicht angewendet.',
  cannotAddThisCategory:'Sie können diese Kategorie nicht hinzufügen, da sie noch keine Unterkategorien enthält. Bitte fügen Sie weitere Kategorien hinzu.',
  allOrders:'Alles',
  yearlyRfqLimit:'Jährliches RFQs-Limit',
  contactPersonDetails:'Ansprechpartner Details',
  name:'Name',
  contactPersonCannotBeEmpty:'Ansprechpartnerdetails können nicht leer sein',
  quickDetails:'Schnelle Details',
  label:'Etikette',
  value:'Wert',
  addMore:'Mehr hinzufügen',
  pending:'steht aus',
  profileVerification:'Profilverifizierung',
  profileApproval:'Profilgenehmigung',
  confirmed:'Bestätigte Bestellungen',
  shippedOrders:'Lieferaufträge',
  deliveredOrders:'Gelieferte Bestellungen',
  rejectedOrders:'Abgelehnte Bestellungen',
  cancelledOrders:'Abgebrochene Bestellungen',
  noOrdersFound:'Keine Bestellungen gefunden',
  checkout:'AUSCHECKEN',
  orderShippedd:'Bestellung versandt',
  confirmedd:'Bestätigt',
  cancelled:'Abgebrochen',
  paymentSuccessfull:'BEZAHLUNG ERFOLGREICH',
  allOrdersTitle:'ALLE BESTELLUNGEN',
  allOrdersTitle:'ALLE BESTELLUNGEN',
  from:'von',
  minOrder:'Min. Bestellung',
  allOrders:'Alles',
  waitingForContractDraft:'Warten auf Vertragsentwurf',
  waitingForOrderConfirmation:"Warten auf Bestellbestätigung",
  waitingForPayment:'Warte auf Zahlung',
  waitingForPaymentConfirmation:'Warte auf Zahlungsbestätigung',
  waitingForShipment:'Auf Sendung warten',
  waitingForDeliveryConfirmation:'Warten auf Lieferbestätigung',
  orderCancelRequested:'Auftrag storniert angefordert',
  disputeOrRefund:"Streit/Rückerstattung",
  completed:'fertiggestellt',
  closed:'Geschlossen',
  waitingForSupplier:'Warten, bis der Lieferant die Bestellung bestätigt hat',
  waitingForPayment:'Warten auf Zahlung',
  shipped:'Wird versendet',
  delivered:'Geliefert',
  productStatus:'Produktstatus',
  chat:'PLAUDERN',
  supplierAndProductInformation:'Lieferanten- und Produktinformationen',
  total:'Gesamt',
  orderDetails:'Bestelldetails',
  orderNumber:'Bestellnummer',
  orderSubmitted:'Auftrag gesendet',
  cancelOrder:'STORNIEREN',
  track:'SPUR',
  trackOrderTitle:'VERSANDVERFOLGUNG',
  shippingAddress:'Lieferanschrift',
  landmark:'Wahrzeichen',
  buyerAndProductInformation:'Käufer- und Produktinformationen',
  reject:'ABLEHNEN',
  accept:'AKZEPTIEREN',
  rejectOrder:'REJECT ORDER',
  acceptOrder:'Bestellung annehmen',
  orderDetailsTitle:'BESTELLDETAILS',
  track:'TRACK',
  key:'Schlüssel',
  quickDetailsEx:'(ex-Farbe: schwarz)',
  customerReviews:'Kundenbewertungen',
  customerReview:'Kundenbewertung',
  allReviewsTitle:'ALLE BEWERTUNGEN',
  productPreview:'Produktvorschau',
  show:'SHOW',
  productPreviewTitle:'PRODUKTVORSCHAU',
  supplierProfile:'Lieferantenprofil',
  view:'Aussicht',
  contactPerson:'Gesprächspartner',
  ratingsReviews:'Bewertungen und Bewertungen',
  recentlyAddedReviews:'Kürzlich hinzugefügte Bewertungen',
  thisProductHasNoReview:'Entschuldigung, dieses Produkt hat keine Bewertung',
  days:'Tage',
  perQuantity:'pro Menge',
  rfqDetails:'Rfq Details -',
  myQuotation:'Mein Zitat',
  inDays:'in Tagen',
  notAdded:'Nicht hinzugefügt',
  viewTermsConditions:'Allgemeine Geschäftsbedingungen anzeigen',
  by:'durch',
  paymentSuccessfull:'BEZAHLUNG ERFOLGREICH',
  planUpgradedSuccessfully:'Sie haben Ihren Plan aktualisiert',
  pleaseWaitPaymentMsg:'Bitte warten Sie, während wir Ihre Anfrage bearbeiten ...',
  activePlan:'Aktiver Plan',
  productUsed:'Produkt verwendet',
  storageUsed:'Speicher verwendet',
  storageRemaining:'Lagerung bleibt erhalten',
  rfqUsed:'RFQ verwendet',
  rfqRemaining:'RFQ übrig',
  noActivePlan:"Sie haben keinen Mitgliedschaftsplan gekauft. Wählen Sie ein Mitgliedschaftspaket, mit dem Sie sofort Vertrauen von Käufern erhalten",
  sellerShare:'Verkäufer teilen',
  commission:'Kommission',
  productDimensions:'Produktabmessungen',
  weight:'Gewicht(in Gramm)',
  width:'Breite(in Zoll)',
  height:'Höhe(in Zoll)',
  depth:'Tiefe(in Zoll)',
  pleaseEnterDimensions:'Bitte fügen Sie Produktabmessungen hinzu',
  myReferences:'Meine Referenzen',
  noReferencesAdded:'Keine Referenzen hinzugefügt',
  addReferences:'Fügen Sie Referenzen hinzu',
  clientInformation:'Kundeninformationen',
  shortNote:'Schreibe eine kurze Notiz',
  yourReferenceCreatedSuccessfully:'Ihre Referenz wurde erfolgreich erstellt',
  unableToOpen:'UNFÄHIG ZU ÖFFNEN',
  urlIsNotCorrect:'Url ist nicht korrekt',
  yourReferenceSavedSuccessfully:'Ihre Referenz wurde erfolgreich gespeichert',
  orderPlaced:'Ihre Zahlung wurde erfolgreich ausgeführt',
  shippingOrders:'Versandaufträge',
  payments:'Zahlungen',
  personalDetails:'Persönliche Details',
  companyDetails:'Firmendaten',
  kycSubmitConfirm:'Möchten Sie das KYC-Formular wirklich senden?',
  kycSubmittedSuccessfully:'Ihr KYC wurde erfolgreich übermittelt. Sie werden benachrichtigt, sobald wir Ihren Status bearbeitet haben',
  packageDimensions: 'Paketmaße',
  length: 'Länge(in Zoll)',
  units: 'Einheiten(in Anzahl)',
  shippingOptions: 'Versandart',
  shippingCharges: 'Versandkosten',
  listPrice: 'Listenpreis',
  grandTotal: 'Gesamtsumme',
  productTermsConditions: 'Produktbedingungen',
  enterTermsConditions: 'Geben Sie die Allgemeinen Geschäftsbedingungen ein',

}
