export const it={
  login:"ACCESSO",
  register:"REGISTRARE",
  username:"Nome utente",
  email:"E-mail",
  mobile:"Mobile",
  password:"Parola d'ordine",
  confirmPassword:"conferma password",
  signup:"ISCRIVITI",
  otpMessage:"Inserisci l'OTP a 4 cifre inviato al tuo cellulare",
  enterOTP:"Inserisci OTP",
  verify:"VERIFICARE",
  resendOTP:"Reinvia verifica OTP",
  emailOrusername:"Email/Username",
  continueWithFb:"CONTINUA CON FACEBOOK",
  continueWithGoogle:"CONTINUA CON GOOGLE",
  forgotPassword:"HA DIMENTICATO LA PASSWORD?",
  enterMobile:"Inserisci il tuo numero di cellulare registrato",
  verify:"VERIFICARE",
  trendingProducts:"I migliori prodotti di tendenza",
  lightEquipmentTools:"STRUMENTI DI ATTREZZATURA LEGGERA",
  foodProducts:"PRODOTTI ALIMENTARI E AL DETTAGLIO",
  latestProducts:"GLI ULTIMI PRODOTTI",
  recommendedProducts:"PRODOTTI CONSIGLIATI",
  topRatedProducts:"PRODOTTI TOP RATED",
  heavyEquipmentTools:"STRUMENTI PESANTI",
  products:"PRODOTTI",
  suppliers:"FORNITORI",
  searchProducts:"Cerca prodotti",
  searchSuppliers:"Cerca fornitori",
  recentSearches:"Ricerche recenti",
  popularSearches:"Ricerche popolari",
  results:"risultati",
  contact:"Contatto",
  productDetails:"DETTAGLI DEL PRODOTTO",
  companyProfile:"Profilo Aziendale",
  follow:"SEGUIRE",
  visitProfile:"VISITA IL PROFILO",
  itemDetails:"DETTAGLI DELL'OGGETTO",
  detailsPicture:"Dettagli Immagine",
  recommendedFromThisSupplier:"Consigliato da questo fornitore",
  recommendedFromOtherSupplier:"Consigliato da altri fornitori",
  sendEnquiry:"INVIA RICHIESTA",
  chatNow:"CHATTA ADESSO",
  sendEnquiry:"INVIA RICHIESTA",
  attachPhotos:"Allegare foto",
  recommendOtherSuppliers:"Consiglia altri fornitori corrispondenti se questo fornitore non mi contatta entro 24 ore.",
  agreeToShareContactInfo:"Accetto di condividere le mie informazioni di contatto nel mio profilo acquirente con il fornitore.",
  send:"INVIARE",
  accounts:"CONTI",
  manageOrders:"Gestisci gli ordini",
  favourites:"Preferiti",
  quotations:"Le vostre citazioni",
  buyingRequest:"Richiesta d'acquisto",
  profileDetails:"Dettagli del profilo",
  settings:"impostazioni",
  aboutUs:"Riguardo a noi",
  TC:"Termini & Condizioni",
  privacyPolicy:"politica sulla riservatezza",
  contactUs:"Contattaci",
  profileDetailsTitle:"DETTAGLI DEL PROFILO",
  firstName:"Nome di battesimo",
  lastName:"Cognome",
  contactNumber:"Numero di contatto",
  changePassword:"CAMBIA LA PASSWORD",
  updateDetails:"AGGIORNARE I DETTAGLI",
  otp:"OTP",
  newPassword:"nuova password",
  save:"SALVARE",
  language:"linguaggio",
  notifications:"notifiche",
  languageTitle:"LINGUAGGIO",
  companyName:"Nome della ditta",
  location:"Posizione",
  logout:'DISCONNETTERSI',
  welcome:'Benvenuto in Brown Eagle',
  loginOrSignup:'Accedi o registrati per piacere, raccogliere e gestire gli ordini',
  continueWith:'CONTINUA CON',
  fb:'FACEBOOK',
  google:'GOOGLE',
  enterEmail:'Inserisci il tuo indirizzo email',
  emailSent:"Un'email di conferma è stata inviata alla tua casella di posta",
  checkEmail:'Bitte überprüfen Sie Ihre E-Mail.',
  resendEmail:"Rinvia l'e-mail",
  notReceiveEmail:'Hai problemi a ricevere email',
  clickHere:'Clicca qui',
  manageProducts:'Gestisci prodottos',
  manageProductsTitle:'Gestisci prodottos',
  manageBusiness:'Gestisci affari',
  allProducts:'Tutti i prodotti',
  approvedProducts:'Prodotti approvati',
  approvedProductsTitle:'Prodotti approvati',
  approvalPending:'In attesa di approvazione',
  rejectedProducts:'Prodotti rifiutati',
  rejectedProductsTitle:'Prodotti rifiutati',
  addNewProduct:'AGGIUNGI UN NUOVO PRODOTTO',
  allProductsTitle:'TUTTI I PRODOTTI',
  productNameCannotEmpty:'Il nome del prodotto non può essere vuoto',
  ok:'OK',
  pleaseEnterKeyword:'Inserisci almeno una parola chiave del prodotto',
  productCatCannotEmpty:'La categoria di prodotto non può essere vuota',
  productSubCatCannotEmpty:'La categoria secondaria del prodotto non può essere vuota',
  addProductDescription:'Aggiungi una descrizione del prodotto',
  productQualityCannotBeEmpty:'La quantità minima del prodotto non può essere vuota',
  addProductPrice:'Aggiungi un prezzo del prodotto',
  basicInformation:'Informazioni di base',
  productName:'nome del prodotto',
  productKeywords:'Parole chiave del prodotto',
  catInformation:'Informazioni sulla categoria',
  category:'Categoria',
  searchCat:'Cerca categorie',
  subCat:'Sottocategoria',
  productDetailsInformation:'Informazioni sui dettagli del prodotto',
  productPhoto:'Foto del prodotto / Video',
  productDescription:'Descrizione del prodotto',
  requirement:'Requisiti',
  minQuality:'Quantità minima (ex - 10)',
  productPrice:'Prezzo del prodotto',
  submit:'SOTTOSCRIVI',
  addProductTitle:'AGGIUNGI PRODOTTO',
  cancel:'Annulla',
  fromCamera:'Dalla fotocamera',
  fromLibrary:'Dalla libreria',
  apparel:'Abbigliamento, tessuti e accessori',
  transportation:'Auto e trasporti',
  electronics:'Elettronica',
  machinery:'Macchinari, hardware e strumenti',
  gifts:'Regali, sport e hobby',
  homeLights:'Casa, Luci e Costruzioni',
  healthBeauty:'Salute & Bellezza',
  jewelryBags:'Gioielli, borse e scarpe',
  electricalEquipment:'Materiale elettrico',
  agriculture:'Agricoltura e cibo',
  packaging:'Packaging, pubblicità e ufficio',
  rawProcessing:'Materie prime e lavorate',
  Apparel:'Abbigliamento',
  textile:'Prodotti tessili e in pelle',
  fashion:'Prodotti tessili e in pelle',
  automobiles:'Automobili e motocicli',
  Transportation:'Transporti',
  computer:'Computers',
  consumerElectronics:'Elettronica di consumo',
  homeAppliances:'Elettrodomestici',
  security:'Sicurezza e protezione',
  hardware:'Hardware e strumenti',
  instruments:'Strumenti di misura e analisi',
  Machinery:'macchinario',
  mechanicalParts:'Servizio di parti meccaniche e fabbricazione',
  giftsCrafts:'Regali e artigianato',
  sportsEnternainment:'Sport e intrattenimento',
  toys:'Giocattoli e hobby',
  construction:'Edilizia e patrimonio immobiliare',
  lights:'Luci e illuminazione',
  homeGarden:'Casa e giardino',
  furniture:'mobili',
  healthMedical:'Salute e medicina',
  beautyCare:'Bellezza e cura della persona',
  luggageBags:'Bagagli, borse e valigie',
  timePieces:'Orologi, gioielli, occhiali',
  shoesAccessories:'Scarpe e accessori',
  electricalSuppliers:'Apparecchiature e forniture elettriche',
  elctronicComponents:'Componenti e rifornimenti elettronici',
  telecommunications:'Telecomunicazioni',
  agriculture:'Agricoltura',
  foodBeverage:'Cibo e bevande',
  packagingPrinting:'Imballaggio e stampa',
  schoolSuppliers:'Forniture per ufficio e scuola',
  serviceEquipment:'Attrezzature di servizio',
  mineralsMetallurgy:'Minerali e metallurgia',
  chemicals:'Chemicals',
  rubberPlastic:'Gomma e plastica',
  energy:'energia',
  environment:'ambiente',
  youHaveNotAddedProduct:'Non hai ancora aggiunto alcun prodotto.',
  pendingProducts:'PRODOTTI IN CORSO',
  areYouSure:'Sei sicuro?',
  yes:'sì',
  update:'AGGIORNARE',
  notApproved:'Nessuno dei tuoi prodotti è stato approvato',
  noProductsFound:'Nessun prodotto trovato',
  clickToEdit:'Clicca per modificare',
  haveAnyQues:'Se avete domande su questi Termini, vi preghiamo di contattarci.',
  contact:'CONTATTO',
  address:'BROWN EAGLE INC.\n1000 N West Street\nSuite 1200\nWilmington, DE 19801\nNumero di telefono: 302-295-3816\nNumero di fax: 302-295-4801',
  registeredAddress:'Indirizzo registrato',
  Address:'indirizzo',
  city:'città',
  state:'stato',
  zipCode:'CAP',
  country:'paese',
  operationalAddress:'Indirizzo operativo',
  companyInfo:"Informazioni sull'azienda",
  website:'sito web(ex: http://www.example.com)',
  established:'Establecido',
  employeeCount:'Conta dei dipendenti',
  description:'Descrizione della compagnia',
  emailNotVerified:'EMAIL NON INVIATO',
  verifyNow:'Fai clic su VERIFY per verificare il tuo account BrownEagle',
  later:'più tardi',
  mainProducts:'Prodotti Principali',
  add:'INSERISCI',
  keywordsEx:'(ad esempio: Parola chiave 1, Parola chiave2, Parola chiave3)',
  settingsTitle:'IMPOSTAZIONI',
  TCTtile:'TERMINI & CONDIZIONI',
  contactUsTitle:'CONTATTACI',
  profileNotVerified:'PENDENZA DI VERIFICA DEL PROFILO',
  ok:'OK',
  sameAsRegisteredAddress:"Come l'indirizzo registrato",
  passwordResetMsg:"Per reimpostare la password, è stata inviata un'e-mail alla tua casella di posta",
  account:'cuenta',
  payment:'Pagamento',
  sales:'I saldi',
  support:'Supporto',
  others:'Altri',
  chooseDepartment:'Scegli il Dipartimento',
  message:'Messaggio...',
  rfqTitle:'RICHIESTA DI ACQUISTO',
  searchRfq:'Cerca RFQ',
  rfqDetailsTitle:'DETTAGLI RFQ',
  quantityRequired:'Quantità richiesta',
  availability:'disponibilità',
  datePosted:'Data di pubblicazione',
  detailedDescription:'Descrizione dettagliata',
  emailAlreadyExists:"L'email esiste già",
  enterValidEmail:"Si prega di inserire un indirizzo email valido",
  passwordCannotBeEmpty:'La password non può essere vuota',
  onlyBuyersCanLoggedIn:'Solo gli acquirenti possono accedere.',
  enterValidName:'Si prega di inserire un nome valido',
  enterValidLastName:'Si prega di inserire un cognome valido',
  enterValidContact:'Si prega di inserire un numero di contatto valido',
  passwordLengthError:'La password non può essere inferiore a 6 caratteri',
  passwordNotMatched:'Le tue password non sono state abbinate',
  noUserRegistered:"Nessun utente registrato con l'indirizzo email",
  profileUpdatedSuccessfully:'Dettagli del profilo con successo',
  passwordUpdatedSuccessfully:'Password aggiornata correttamente',
  enterValidCompanyName:'Si prega di inserire un nome di società valido',
  countryOrRegion:'Paese/Regione',
  onlySellersCanLoggedin:'Solo i venditori Brown Eagle possono essere registrati.',
  fetchingLocation:'Recupero noleggio ...',
  noCategoriesFound:'Nessuna categoria trovata',
  noSubcategoriesFound:'Nessuna sottocategoria trovata',
  addressCannotBeEmpty:"L'indirizzo non può essere vuoto",
  operationalAddressCannotBeEmpty:"L'indirizzo operativo non può essere vuoto",
  websiteCannotBeEmpty:'Il sito Web non può essere vuoto',
  establishedCannotBeEmpty:"L'anno stabilito dall'azienda non può essere vuoto",
  employeeCountCannotBeEmpty:'Il conteggio dei dipendenti non può essere vuoto',
  imageExceedsAlert:'Puoi caricare fino a 6 immagini.',
  quantity:'inventario',
  pieces:'unità',
  piece:'unità',
  noRfqFound:'Nessun RFQs trovato',
  subCategory:'Sottocategoria',
  unitPrice:'Prezzo unitario',
  verified:'verificato',
  title:'Titolo',
  delete:'DELETE',
  categoryTitle:'CATEGORIE',
  sendQuotationsTitle:'INVIA LA QUOTAZIONE',
  enterQuantity:'Inserisci una quantità',
  enterUnitPrice:'Inserisci un prezzo unitario',
  productDetail:'Dettagli del prodotto',
  sendProposal:'Invia una proposta',
  deliveryTime:'Tempi di consegna',
  enterDeliveryTime:'Inserire un tempo di consegna (in giorni)',
  quotationsTitle:'LE MIE QUOTATE',
  searchQuotations:'Cerca citazioni',
  QUOTATIONS:"QUOTAZIONI",
  status:'stato',
  all:'tutto',
  open:'aperto',
  rejected:'Rifiutato',
  closed:'chiuso',
  sortBy:'Ordina per',
  startDate:'Data di inizio',
  endDate:'Data di fine',
  quotationDetalisTitle:'DETTAGLI DI QUOTAZIONE',
  shopBy:"Acquista",
  enterTitle:'Inserisci un titolo',
  minQuantity:'Quantità minima',
  quotedPrice:'Prezzo quotato',
  estimatedDeliveryTime:'Tempo di consegna stimato',
  enterMinQuantity:'Inserisci la quantità minima',
  enterEtimatedDeliveryTime:'Inserisci il tempo di consegna stimato',
  coverLetter:'Lettera di presentazione',
  enterCoverLetter:'Inserisci una lettera di accompagnamento',
  pleaseEnterTitle:'Si prega di inserire un titolo',
  pleaseEnterMinQuantity:'Si prega di inserire una quantità minima',
  pleaseEnterQuotedPrice:'Si prega di inserire un prezzo indicato',
  pleaseEnterEstimatedDeliveryTime:'Si prega di inserire i tempi di consegna stimati',
  pleaseEnterCoverLetter:'Si prega di inviare una lettera di copertura',
  quottionSubmittedSuccessfully:'Il tuo preventivo è stato archiviato con successo',
  noQuotationsFound:'Nessuna citazioni trovata',
  membershipPlan:'Piano di aggiornamento',
  membershipPlanTitle:'PIANO DI MEMBRO',
  expandBusiness:"Diamo Espandi la tua attività che ti aiuta ad ottenere una fiducia immediata dagli acquirenti",
  chooseMembershipPackage:'Scegli un pacchetto di iscrizione',
  noPackagesAtYourLocation:'Nessun piano nella tua posizione',
  package:'pacchetto',
  storage:'Conservazione al mese',
  nextRenewal:'Prossimo rinnovo',
  unSubscribePlan:"Annulla l'iscrizione al piano",
  subscribePlan:'Iscriviti al piano',
  subscribeConfirm:"Vuoi davvero iscriverti al piano?",
  unSubscribeConfirm:"Vuoi annullare l'iscrizione al piano?",
  subscriptionFailed:"Impossibile annullare l'iscrizione al piano. Riprova più tardi",
  expireOn:'Scade il',
  productListing:'Elenchi di prodotti totali',
  detailsTitle:'DETTAGLI',
  packageCost:'Costo del pacchetto',
  service:'servizio',
  serviceType:'Tipo di servizio',
  serviceCost:'Costo del servizio',
  upgradeNow:'AGGIORNA ORA',
  upload:'Carica',
  video:'Video',
  myCertificates:'I miei certificati',
  myCertificatesTitle:'I MIEI CERTIFICATI',
  noCertificatesUploaded:'Nessun certificato caricato',
  addCertificate:'AGGIUNTA DI CERTIFICATO',
  viewCertificateTitle:'VISTA',
  clickToView:'Clicca per vedere',
  certificateTitle:'TITOLO DEL CERTIFICATO',
  somethingWentWrong:'Qualcosa è andato storto. Si prega di riprovare più tardi',
  titleCannotBeEmpty:"Il titolo non può essere vuoto",
  certificateUploadedSuccessfully:'Il tuo certificato è stato caricato con successo',
  myVideosTitle:'COPRI IL VIDEO',
  myVideos:'Coprire video',
  noVideosUploaded:'Nessun video di copertina trovato',
  addVideo:'AGGIUNGI ORA',
  canUploadOnlyOneVideo:'Puoi caricare solo 1 video',
  brownEagleWillCharge:'Brown Eagle addebiterà',
  commissionForThisCategory:'commissione per questa categoria',
  termsAndConditionsApplied:'Termini e condizioni applicati',
  noTermsFound:'Termini e condizioni non sono applicati.',
  cannotAddThisCategory:'Non è possibile aggiungere questa categoria poiché non contiene ancora sottocategorie. Per favore aggiungi altre categorie.',
  allOrders:'Tutto',
  yearlyRfqLimit:'Limite annuale RFQ',
  contactPersonDetails:'Dettagli della persona di contatto',
  name:'Nome',
  contactPersonCannotBeEmpty:'I dettagli della persona di contatto non possono essere vuoti',
  quickDetails:'Info Veloci',
  label:'Etichetta',
  value:'Valore',
  addMore:'Aggiungere altro',
  pending:'in attesa di',
  profileVerification:'Verifica del profilo',
  profileApproval:'Approvazione profilo',
  confirmed:'Ordini confermati',
  shippedOrders:'Ordini spediti',
  deliveredOrders:'Ordini consegnati',
  rejectedOrders:'Ordini rifiutati',
  cancelledOrders:'Ordini annullati',
  noOrdersFound:'Nessun ordine trovato',
  checkout:'CHECK-OUT',
  orderShippedd:'Ordine spedito',
  confirmedd:'Confermato',
  cancelled:'Annullato',
  paymentSuccessfull:'PAGAMENTO DI SUCCESSO',
  allOrdersTitle:'TUTTI GLI ORDINI',
  from:'a partire dal',
  minOrder:'Min. Ordine',
  allOrders:'Tutto',
  waitingForContractDraft:"In attesa di una bozza di contratto",
  waitingForOrderConfirmation:"In attesa di conferma d'ordine",
  waitingForPayment:'In attesa di pagamento',
  waitingForPaymentConfirmation:'In attesa di conferma del pagamento',
  waitingForShipment:'In attesa di spedizione',
  waitingForDeliveryConfirmation:'In attesa di conferma di consegna',
  orderCancelRequested:'Ordine annullato richiesto',
  disputeOrRefund:"Contestazione/rimborso",
  completed:'completato',
  closed:'chiuso',
  waitingForSupplier:"In attesa che il fornitore confermi l'ordine",
  waitingForPayment:'In attesa del pagamento',
  shipped:'Spedito',
  delivered:'consegnato',
  productStatus:'Stato del prodotto',
  chat:'CHIACCHIERARE',
  supplierAndProductInformation:'Informazioni su prodotti e fornitori',
  total:'Totale',
  orderDetails:'Dettagli ordine',
  orderNumber:"Numero d'ordine",
  orderSubmitted:'Ordine inviato',
  cancelOrder:'ANNULLA',
  track:'TRACCIA',
  trackOrderTitle:'ORDINE DEI BRANI',
  shippingAddress:'indirizzo di spedizione',
  landmark:'Punto di riferimento',
  buyerAndProductInformation:"Informazioni sull'acquirente e sul prodotto",
  reject:'RIFIUTARE',
  accept:'ACCETTARE',
  rejectOrder:"RIFIUTARE L'ORDINE",
  acceptOrder:"ACCETTARE L'ORDINE",
  orderDetailsTitle:"DETTAGLI DELL'ORDINE",
  track:'TRACK',
  key:'chiave',
  quickDetailsEx:'(ex- Colore: nero)',
  customerReviews:'Recensioni dei clienti',
  customerReview:'Revisione del cliente',
  allReviewsTitle:'TUTTE LE RECENSIONI',
  productPreview:'Anteprima del prodotto',
  show:'MOSTRA',
  productPreviewTitle:'ANTEPRIMA DEL PRODOTTO',
  supplierProfile:'Profilo del fornitore',
  view:'vista',
  contactPerson:'Referente',
  ratingsReviews:'Valutazioni e recensioni',
  recentlyAddedReviews:'Recensioni aggiunte di recente',
  thisProductHasNoReview:'Siamo spiacenti, questo prodotto non ha recensioni',
  days:'giorni',
  perQuantity:'per quantità',
  rfqDetails:'Dettagli Rfq -',
  myQuotation:'La mia citazione',
  inDays:'in pochi giorni',
  notAdded:'Non aggiunto',
  viewTermsConditions:'Visualizza termini e condizioni',
  by:'da',
  paymentSuccessfull:'PAGAMENTO DI SUCCESSO',
  planUpgradedSuccessfully:'Hai aggiornato il tuo piano',
  pleaseWaitPaymentMsg:'Per favore attendi mentre elaboriamo la tua richiesta ...',
  activePlan:'Piano attivo',
  productUsed:'Prodotto utilizzato',
  storageUsed:'Deposito utilizzato',
  storageRemaining:'Conservazione rimanente',
  rfqUsed:'RFQ usato',
  rfqRemaining:'RFQ rimanente',
  noActivePlan:"Non hai acquistato alcun piano di adesione. Scegli un pacchetto di iscrizione che ti aiuti ad ottenere una fiducia immediata dagli acquirenti",
  sellerShare:'Condividi venditore',
  commission:'commissione',
  productDimensions:'Dimensioni del prodotto',
  weight:'Peso(in grammi)',
  width:'Larghezza(in pollici)',
  height:'Altezza(in pollici)',
  depth:'Profondità(in pollici)',
  pleaseEnterDimensions:'Por favor agregue dimensiones del producto',
  myReferences:'Le mie referenze',
  noReferencesAdded:'Nessun riferimento aggiunto',
  addReferences:'AGGIUNGI RIFERIMENTI',
  clientInformation:'Informazioni sul cliente',
  shortNote:'Scrivi una breve nota',
  yourReferenceCreatedSuccessfully:'Il tuo riferimento è stato creato con successo',
  unableToOpen:'IMPOSSIBILITATO AD APRIRE',
  urlIsNotCorrect:"L'URL non è corretto",
  yourReferenceSavedSuccessfully:'Il tuo riferimento è stato salvato con successo',
  orderPlaced:'Il tuo pagamento è stato effettuato con successo',
  shippingOrders:'Ordini di spedizione',
  payments:'Pagamenti',
  personalDetails:'Dettagli personali',
  companyDetails:'Dettagli della compagnia',
  kycSubmitConfirm:'Vuoi inviare il modulo KYC?',
  kycSubmittedSuccessfully:'Il tuo KYC è stato inviato con successo. Riceverai una notifica dopo aver elaborato il tuo stato',
  packageDimensions: 'Dimensioni del pacchetto',
  length: 'lunghezza(in pollici)',
  units: 'Unità(in numero)',
  shippingOptions: 'Metodo di spedizione',
  shippingCharges: 'Spese di spedizione',
  listPrice: 'Prezzo di listino',
  grandTotal: 'Totale generale',
  productTermsConditions: 'Termini e condizioni del prodotto',
  enterTermsConditions: 'Inserisci i termini e le condizioni',

}
