export const nl={
  login:"LOG IN",
  register:"REGISTREREN",
  username:"Gebruikersnaam",
  email:"E-mail",
  mobile:"mobiel",
  password:"Wachtwoord",
  confirmPassword:"bevestig wachtwoord",
  signup:"INSCHRIJVEN",
  otpMessage:"Voer 4 cijfers OTP naar uw mobiele",
  enterOTP:"Voer OTP",
  verify:"VERIFIËREN",
  resendOTP:"Opnieuw verzenden Verificatie OTP",
  emailOrusername:"Email / Login",
  continueWithFb:"VERDER MET FACEBOOK",
  continueWithGoogle:"VERDER MET GOOGLE",
  forgotPassword:"WACHTWOORD VERGETEN?",
  enterMobile:"Voer uw geregistreerde mobiele nummer",
  verify:"VERIFIËREN",
  trendingProducts:"TOP TRENDING PRODUCTEN",
  lightEquipmentTools:"Licht apparatuur TOOLS",
  foodProducts:"FOOD & RETAIL PRODUCTS",
  latestProducts:"NIEUWSTE PRODUCTEN",
  recommendedProducts:"AANGERADEN PRODUCTEN",
  topRatedProducts:"TOP RATED PRODUCTS",
  heavyEquipmentTools:"Zwaar materieel TOOLS",
  products:"PRODUCTEN",
  suppliers:"LEVERANCIERS",
  searchProducts:"zoek producten",
  searchSuppliers:"Zoeken leveranciers",
  recentSearches:"recente zoekopdrachten",
  popularSearches:"populaire zoekopdrachten",
  results:"uitslagen",
  contact:"Contact",
  productDetails:"PRODUCTDETAILS",
  companyProfile:"Bedrijfsprofiel",
  follow:"VOLGEN",
  visitProfile:"Bekijk profiel",
  itemDetails:"ONDERDEEL DETAILS",
  detailsPicture:"Details Foto",
  recommendedFromThisSupplier:"Aanbevolen van deze leverancier",
  recommendedFromOtherSupplier:"Aanbevolen van andere leveranciers",
  sendEnquiry:"STUUR ONDERZOEK",
  chatNow:"PRAAT NU",
  sendEnquiry:"STUUR ONDERZOEK",
  attachPhotos:"Voeg foto's",
  recommendOtherSuppliers:"Aan andere passende leveranciers als deze leverancier mij niet binnen 24 uur contact.",
  agreeToShareContactInfo:"Ik ga akkoord met mijn contactinformatie in mijn KOPERSPROFIEL met de leverancier te delen.",
  send:"STUREN",
  accounts:"REKENINGEN",
  manageOrders:"Manage Orders",
  favourites:"favorieten",
  quotations:"uw Citaten",
  buyingRequest:"Buying Request",
  profileDetails:"profiel details",
  settings:"instellingen",
  aboutUs:"Over ons",
  TC:"algemene voorwaarden",
  privacyPolicy:"Privacybeleid",
  contactUs:"Neem contact op",
  profileDetailsTitle:"PROFIEL DETAILS",
  firstName:"Voornaam",
  lastName:"Achternaam",
  contactNumber:"Contact nummer",
  changePassword:"WIJZIG WACHTWOORD",
  updateDetails:"UPDATE DETAILS",
  otp:"OTP",
  newPassword:"nieuw paswoord",
  save:"OPSLAAN",
  language:"Taal",
  notifications:"meldingen",
  languageTitle:"TAAL",
  companyName:"Bedrijfsnaam",
  location:"Plaats",
  logout:"UITLOGGEN",
  welcome:"Welkom bij Brown Eagle",
  loginOrSignup:"Log in of meld je aan wilt",
  continueWith:"VERDERGAAN MET",
  fb:"FACEBOOK",
  google:"GOOGLE",
  enterEmail:"Vul alstublieft uw e-mail adres in",
  emailSent:"Een bevestigings e-mail is verzonden naar uw mailbox",
  checkEmail:"Controleer uw e-mail.",
  resendEmail:"Email opnieuw verzenden",
  notReceiveEmail:"Na probleem ontvangen van e-mail?",
  clickHere:"Klik hier",
  manageProducts:"Manage producten",
  manageProductsTitle:"Producten beheren",
  manageBusiness:"het beheer van zakelijke",
  allProducts:"Alle producten",
  approvedProducts:"goedgekeurde producten",
  approvedProductsTitle:"goedgekeurde producten",
  approvalPending:"In afwachting van goedkeuring",
  rejectedProducts:"afgekeurde producten",
  rejectedProductsTitle:"afgekeurde producten",
  addNewProduct:"Voeg een nieuw product",
  allProductsTitle:"ALLE PRODUCTEN",
  productNameCannotEmpty:"Productnaam mag niet leeg zijn",
  ok:"OK",
  pleaseEnterKeyword:"Voer ten minste één product en zoekwoord",
  productCatCannotEmpty:"Productcategorie mag niet leeg zijn",
  productSubCatCannotEmpty:"Product subcategorie mag niet leeg zijn",
  addProductDescription:"Voeg een product beschrijving",
  productQualityCannotBeEmpty:"Product minimumhoeveelheid mag niet leeg zijn",
  addProductPrice:"Voeg een product prijs",
  basicInformation:"Basis informatie",
  productName:"productnaam",
  productKeywords:"product Trefwoorden",
  catInformation:"categorie Informatie",
  category:"Categorie",
  searchCat:"Zoeken Categorieën",
  subCat:"sub Categorie",
  productDetailsInformation:"Uitgebreide informatie",
  productPhoto:"Product Foto / Video",
  productDescription:"Productomschrijving",
  requirement:"eis",
  minQuality:"Minimum Hoeveelheid (ex - 10)",
  productPrice:"Product prijs",
  submit:"SUBMIT",
  addProductTitle:"ADD PRODUCT",
  cancel:"Annuleer",
  fromCamera:"van camera",
  fromLibrary:"vanaf Bibliotheek",
  apparel:"Kleding",
  transportation:"Auto & Vervoer",
  electronics:"Elektronica",
  machinery:"machinerie",
  gifts:"Cadeaus",
  homeLights:"Huis",
  healthBeauty:"gezondheid & schoonheid",
  jewelryBags:"Juwelen",
  electricalEquipment:"Elektrische apparatuur",
  agriculture:"Landbouw & Food",
  packaging:"Packaging",
  rawProcessing:"Raw & verwerkte materialen",
  Apparel:"Kleding",
  textile:"Textiel & Leather Products",
  fashion:"Mode accessoires",
  automobiles:"Auto's en motoren",
  Transportation:"vervoer",
  computer:"computers",
  consumerElectronics:"Consumentenelektronica",
  homeAppliances:"Huishoudelijke apparaten",
  security:"Beveiliging",
  hardware:"Hardware tools",
  instruments:"Measurement & Analyse Instrumenten",
  Machinery:"machinerie",
  mechanicalParts:"Mechanische onderdelen en fabricage Dienst",
  giftsCrafts:"Gifts & Crafts",
  sportsEnternainment:"Sports & Entertainment",
  toys:"Speelgoed en Hobby",
  construction:"Bouw & Vastgoed",
  lights:"Lights & Lighting",
  homeGarden:"Huis",
  furniture:"Meubilair",
  healthMedical:"Gezondheid en Medisch",
  beautyCare:"Beauty & Personal Care",
  luggageBags:"Bagage",
  timePieces:"uurwerken",
  shoesAccessories:"Shoes & Accessories",
  electricalSuppliers:"Electrical Equipment & Supplies",
  elctronicComponents:"Elektronica",
  telecommunications:"telecommunicatie",
  agriculture:"landbouw",
  foodBeverage:"Eten & Drinken",
  packagingPrinting:"Verpakking & Printing",
  schoolSuppliers:"Kantoor & School Supplies",
  serviceEquipment:"service Equipment",
  mineralsMetallurgy:"Mineralen & Metallurgie",
  chemicals:"Chemicaliën",
  rubberPlastic:"Rubber & Plastics",
  energy:"Energie",
  environment:"Milieu",
  youHaveNotAddedProduct:"U hebt geen product nog niet toegevoegd.",
  pendingProducts:"PENDING PRODUCTEN",
  areYouSure:"Weet je zeker dat?",
  yes:"Ja",
  update:"BIJWERKEN",
  notApproved:"Geen van uw producten is goedgekeurd",
  noProductsFound:"Geen producten gevonden",
  clickToEdit:"Klik om te bewerken",
  haveAnyQues:"Als u vragen heeft over deze voorwaarden",
  contact:"CONTACT",
  address:"BROWN EAGLE INC. \ N1000 N West Street \ nSuite 1200 \ nWilmington",
  registeredAddress:"Geregistreerd adres",
  Address:"Adres",
  city:"stad",
  state:"Staat",
  zipCode:"Postcode",
  country:"land",
  operationalAddress:"operationele Adres",
  companyInfo:"bedrijfsinformatie",
  website:"Website (ex: http://www.example.com)",
  established:"Gevestigd",
  employeeCount:"Employee Count",
  description:"bedrijfsomschrijving",
  emailNotVerified:"EMAIL NIET GECONTROLEERD",
  verifyNow:"Klik op Controleren om uw BrownEagle account te verifiëren",
  later:"Later",
  mainProducts:"hoofd producten",
  add:"TOEVOEGEN",
  keywordsEx:"(Bijvoorbeeld: Trefwoord1",
  settingsTitle:"INSTELLINGEN",
  TCTtile:"ALGEMENE VOORWAARDEN",
  contactUsTitle:"NEEM CONTACT OP",
  profileNotVerified:"PROFIEL In afwachting van verificatie",
  ok:"OK",
  sameAsRegisteredAddress:"Zelfde als geregistreerd adres",
  passwordResetMsg:"Om uw wachtwoord te resetten",
  account:"Account",
  payment:"Betaling",
  sales:"verkoop",
  support:"Ondersteuning",
  others:"anderen",
  chooseDepartment:"Kies Department",
  message:"Bericht...",
  rfqTitle:"KOPEN AANVRAAG",
  searchRfq:"Zoeken RFQ",
  rfqDetailsTitle:"RFQ DETAILS",
  quantityRequired:"Hoeveelheid Vereist",
  availability:"Beschikbaarheid",
  datePosted:"datum geplaatst",
  detailedDescription:"gedetailleerde beschrijving",
  quoteNow:"QUOTE NU",
  emailAlreadyExists:"E-mail bestaat al",
  enterValidEmail:"Vul een geldig e-mailadres in",
  passwordCannotBeEmpty:"Wachtwoord mag niet leeg zijn",
  onlyBuyersCanLoggedIn:"Alleen kopers kunnen ingelogd.",
  enterValidName:"Geef een geldige voornaam",
  enterValidLastName:"Geef alstublieft een geldige achternaam",
  enterValidContact:"Geef een geldig telefoonnummer",
  passwordLengthError:"Wachtwoord mag niet lager zijn dan 6 tekens",
  passwordNotMatched:"Uw wachtwoorden didnot geëvenaard",
  noUserRegistered:"Geen geregistreerde gebruiker met het e-mailadres",
  profileUpdatedSuccessfully:"Profiel informatie bijgewerkt",
  passwordUpdatedSuccessfully:"Wachtwoord succesvol bijgewerkt",
  enterValidCompanyName:"Geef een geldige bedrijfsnaam",
  countryOrRegion:"Land / Regio",
  onlySellersCanLoggedin:"Alleen Brown Eagle verkopers kunnen ingelogd.",
  fetchingLocation:"Ophalen locatie ...",
  noCategoriesFound:"Geen categorieën gevonden",
  noSubcategoriesFound:"Geen subcategorieën gevonden",
  addressCannotBeEmpty:"Geregistreerde adres mag niet leeg zijn",
  operationalAddressCannotBeEmpty:"Operationele adres mag niet leeg zijn",
  websiteCannotBeEmpty:"Website mag niet leeg zijn",
  establishedCannotBeEmpty:"Company opgericht jaar mag niet leeg zijn",
  employeeCountCannotBeEmpty:"Aantal personeelsleden mag niet leeg zijn",
  imageExceedsAlert:"U kunt uploaden tot 6 beelden.",
  quantity:"quant",
  pieces:"units",
  piece:"eenheid",
  noRfqFound:"Geen RFQ's gevonden",
  subCategory:"sub Categorie",
  unitPrice:"Eenheid prijs",
  verified:"geverifieerde",
  title:"Titel",
  delete:"DELETE",
  categoryTitle:"CATEGORIEËN",
  sendQuotationsTitle:"SEND OFFERTE",
  enterQuantity:"Voer een hoeveelheid",
  enterUnitPrice:"Voer een eenheidsprijs",
  productDetail:"Productdetails",
  sendProposal:"Stuur een voorstel",
  deliveryTime:"Aflevertijd",
  enterDeliveryTime:"Voer een levertijd (in dagen)",
  quotationsTitle:"MIJN OFFERTES",
  searchQuotations:"Zoek Citaten",
  QUOTATIONS:"OFFERTES",
  status:"staat",
  all:"Alle",
  open:"Open",
  rejected:"Verworpen",
  closed:"Gesloten",
  sortBy:"Sorteer op",
  startDate:"Begin datum",
  endDate:"Einddatum",
  quotationDetalisTitle:"OFFERTE DETAILS",
  shopBy:"Kopen bij",
  enterTitle:"Voer een titel",
  minQuantity:"Minimale hoeveelheid",
  quotedPrice:"Genoteerde prijs",
  estimatedDeliveryTime:"Geschatte Leveringstijd",
  enterMinQuantity:"Voer minimum quntity",
  enterEtimatedDeliveryTime:"Voer geschatte levertijd",
  coverLetter:"Voorblad",
  enterCoverLetter:"Voer een begeleidende brief",
  pleaseEnterTitle:"Voer een titel",
  pleaseEnterMinQuantity:"Vul een minimumhoeveelheid",
  pleaseEnterQuotedPrice:"Geef een genoteerde prijs",
  pleaseEnterEstimatedDeliveryTime:"Vul geschatte levertijd",
  pleaseEnterCoverLetter:"Stuur dan een sollicitatiebrief",
  quottionSubmittedSuccessfully:"Uw offerte is verzonden",
  noQuotationsFound:"Geen citaten gevonden",
  membershipPlan:"upgrade Plan",
  membershipPlanTitle:"LIDMAATSCHAP PLAN",
  expandBusiness:"Laten we uw activiteiten uitbreiden die helpt u onmiddellijk het vertrouwen van kopers te krijgen",
  chooseMembershipPackage:"Kies een Membership Package",
  noPackagesAtYourLocation:"Geen plannen op uw locatie",
  package:"Pakket",
  storage:"Opslag per maand",
  nextRenewal:"Volgende Vernieuwing",
  expireOn:"Vervallen op",
  unSubscribePlan:"Afmelden Plan",
  subscribePlan:"Abonneren Plan",
  subscribeConfirm:"Zijn er zeker van wil om het plan in te schrijven?",
  unSubscribeConfirm:"Zijn er zeker van wil om het plan af te melden?",
  subscriptionFailed:"Kan het plan Afmelden",
  productListing:"Totaal Productvermeldingen",
  detailsTitle:"DETAILS",
  packageCost:"pakket Cost",
  service:"Service",
  serviceType:"Dienst Type",
  serviceCost:"dienst Cost",
  upgradeNow:"WAARDEER NU OP",
  upload:"Uploaden",
  video:"Video",
  myCertificates:"mijn Certificaten",
  myCertificatesTitle:"MY CERTIFICATEN",
  noCertificatesUploaded:"Geen Certificaten Uploaded",
  addCertificate:"ADD CERTIFICAAT",
  viewCertificateTitle:"UITZICHT",
  clickToView:"Klik om te bekijken",
  certificateTitle:"CERTIFICAAT TITEL",
  somethingWentWrong:"Er is iets fout gegaan. Probeer het later opnieuw",
  titleCannotBeEmpty:"Titel mag niet leeg zijn",
  certificateUploadedSuccessfully:"Uw certificaat is geüpload",
  myVideosTitle:"COVER VIDEO",
  myVideos:"Cover Video",
  noVideosUploaded:"Geen dekking video GEVONDEN",
  addVideo:"VOEG NU TOE",
  canUploadOnlyOneVideo:"U kunt uploaden slechts 1 video",
  brownEagleWillCharge:"Brown Eagle rekent",
  commissionForThisCategory:"commissie voor deze rubriek",
  termsAndConditionsApplied:"Voorwaarden Applied",
  noTermsFound:"Voorwaarden zijn niet toegepast.",
  cannotAddThisCategory:"U kunt deze categorie niet toevoegen omdat het geen subcategorieën nog niet bevat. Gelieve te voegen andere categorieën.",
  allOrders:"Alle",
  yearlyRfqLimit:"Jaarlijkse RFQ limiet",
  contactPersonDetails:"Contactpersoon Details",
  name:"Naam",
  contactPersonCannotBeEmpty:"Contactpersoon gegevens mag niet leeg zijn",
  quickDetails:"snelle details",
  label:"Label",
  value:"Waarde",
  addMore:"Voeg meer toe",
  pending:"in afwachting",
  profileVerification:"PROFIEL Verification",
  profileApproval:"profiel Goedkeuring",
  confirmed:"bevestigde orders",
  shippedOrders:"verzonden bestellingen",
  deliveredOrders:"geleverd bestellingen",
  rejectedOrders:"afgewezen bestellingen",
  cancelledOrders:"geannuleerde bestellingen",
  noOrdersFound:"Geen bestellingen gevonden",
  checkout:"UITCHECKEN",
  orderShippedd:"Bestelling verscheept",
  confirmedd:"bevestigd",
  cancelled:"Geannuleerd",
  paymentSuccessfull:"BETALEN SUCCESSFULL",
  allOrdersTitle:"ALLE BESTELLINGEN",
  from:"van",
  minOrder:"Min. Bestellen",
  allOrders:"Alle",
  waitingForContractDraft:"Wachten op contract ontwerp",
  waitingForOrderConfirmation:"Wachten op de orderbevestiging",
  waitingForPayment:"wachten op betaling",
  waitingForPaymentConfirmation:"Wachten op bevestiging van de betaling",
  waitingForShipment:"Wachten voor verzending",
  waitingForDeliveryConfirmation:"Het wachten op de levering bevestiging",
  orderCancelRequested:"Bestelling te annuleren gevraagd",
  disputeOrRefund:"Geschil / Refund",
  completed:"Voltooid",
  closed:"Gesloten",
  waitingForSupplier:"Wachten op leverancier bestelling te bevestigen",
  waitingForPayment:"wachten op betaling",
  shipped:"verzonden",
  delivered:"Geleverd",
  productStatus:"product status",
  chat:"CHAT",
  supplierAndProductInformation:"Leverancier en productinformatie",
  total:"Totaal",
  orderDetails:"Bestel Details",
  orderNumber:"Ordernummer",
  orderSubmitted:"Bestelling ingediend",
  cancelOrder:"ANNULEER",
  track:"TRACK",
  trackOrderTitle:"VOLG BESTELLING",
  shippingAddress:"Verzendingsadres",
  landmark:"mijlpaal",
  buyerAndProductInformation:"Koper en productinformatie",
  reject:"REJECT",
  accept:"AANVAARDEN",
  rejectOrder:"Wijs opdracht af",
  acceptOrder:"ACCEPT ORDER",
  orderDetailsTitle:"BESTEL DETAILS",
  track:"TRACK",
  key:"Sleutel",
  quickDetailsEx:"(Ex- Kleur: Zwart)",
  customerReviews:"klanten-reviews",
  customerReview:"Customer review",
  allReviewsTitle:"ALL REVIEWS",
  productPreview:"product preview",
  show:"TONEN",
  productPreviewTitle:"PRODUCT PREVIEW",
  supplierProfile:"Leverancier profiel",
  view:"Uitzicht",
  contactPerson:"Contactpersoon",
  ratingsReviews:"Ratings & Reviews",
  recentlyAddedReviews:"Onlangs toegevoegde beoordelingen",
  thisProductHasNoReview:"Sorry",
  days:"dagen",
  perQuantity:"per hoeveelheid",
  rfqDetails:"RFQ Details -",
  myQuotation:"mijn offerte",
  inDays:"in dagen",
  notAdded:"Niet toegevoegd",
  viewTermsConditions:"View Algemene Voorwaarden",
  by:"door",
  paymentSuccessfull:"BETALEN SUCCESSFULL",
  planUpgradedSuccessfully:"U heeft uw plan opgewaardeerd",
  pleaseWaitPaymentMsg:"Een ogenblik geduld terwijl we het verwerken van uw verzoek ...",
  activePlan:"actieve Plan",
  productUsed:"gebruikt product",
  storageUsed:"Storage gebruikt",
  storageRemaining:"opslag resterende",
  rfqUsed:"RFQ gebruikt",
  rfqRemaining:"RFQ resterende",
  noActivePlan:"Je hebt niet gekocht geen lidmaatschap plan. Kies een Membership Package die helpt u onmiddellijk het vertrouwen van kopers te krijgen",
  sellerShare:"verkoper Share",
  commission:"Commissie",
  productDimensions:"Productafmetingen",
  weight:"Gewicht (in gram)",
  width:"Breedte (in inches)",
  height:"Hoogte in inches)",
  depth:"Diepte (in inches)",
  pleaseEnterDimensions:"Gelieve te voegen product afmetingen",
  myReferences:"mijn Referenties",
  noReferencesAdded:"Geen referenties toegevoegd",
  addReferences:"ADD Referenties",
  clientInformation:"Klanteninformatie",
  shortNote:"Schrijf een kort briefje",
  yourReferenceCreatedSuccessfully:"Uw referentie is aangemaakt",
  unableToOpen:"KAN NIET GEOPEND WORDEN",
  urlIsNotCorrect:"Url is niet correct",
  yourReferenceSavedSuccessfully:"Uw verzoek is succesvol opgeslagen",
  orderPlaced:"Uw betaling is met succes gemaakt",
  shippingOrders:"scheepvaart bestellingen",
  payments:"betalingen",
  personalDetails:"Persoonlijke gegevens",
  companyDetails:"Bedrijfsgegevens",
  kycSubmitConfirm:"Weet je zeker wilt de KYC formulier?",
  kycSubmittedSuccessfully:"Uw KYC is met succes ingediend. U krijgt bericht zodra wij uw status verwerkt",
  packageDimensions:"pakketafmetingen",
  length:"Lengte (in inches)",
  units:"Eenheden (in aantal)",
  shippingOptions:"Verzendmethode",
  shippingCharges:"Verzendkosten",
  listPrice:"Van Prijs",
  grandTotal:"Eindtotaal",
  productTermsConditions:"Product Algemene Voorwaarden",
  enterTermsConditions:"Voer voorwaarden"
}
