export const pl={
  login:"ZALOGUJ SIĘ",
  register:"ZAREJESTROWAĆ",
  username:"Nazwa Użytkownika",
  email:"E-mail",
  mobile:"mobilny",
  password:"Hasło",
  confirmPassword:"Potwierdź hasło",
  signup:"ZAPISZ SIĘ",
  otpMessage:"Wprowadź 4-cyfrowy OTP wysyłane do telefonu komórkowego",
  enterOTP:"Wprowadź OTP",
  verify:"ZWERYFIKOWAĆ",
  resendOTP:"Wyślij ponownie weryfikacji OTP",
  emailOrusername:"Email / Nazwa użytkownika",
  continueWithFb:"KONTYNUACJA z Facebooka",
  continueWithGoogle:"KONTYNUACJA z Google",
  forgotPassword:"ZAPOMNIAŁEŚ HASŁA?",
  enterMobile:"Wpisz swój numer telefonu komórkowego zarejestrowanego",
  verify:"ZWERYFIKOWAĆ",
  trendingProducts:"TOP trendów PRODUCTS",
  lightEquipmentTools:"ŚWIATŁO sprzętu Narzędzia",
  foodProducts:"FOOD & produktów detalicznych",
  latestProducts:"NAJNOWSZE PRODUKTY",
  recommendedProducts:"REKOMENDOWANE PRODUKTY",
  topRatedProducts:"Najlepiej ocenione PRODUCTS",
  heavyEquipmentTools:"Maszyny rolnicze TOOLS",
  products:"PRODUKTY",
  suppliers:"DOSTAWCY",
  searchProducts:"Szukaj produktów",
  searchSuppliers:"Dostawcy wyszukiwania",
  recentSearches:"Ostatnie wyszukiwania",
  popularSearches:"popularne wyszukiwania",
  results:"wyniki",
  contact:"Kontakt",
  productDetails:"SZCZEGÓŁY PRODUKTU",
  companyProfile:"profil firmy",
  follow:"ŚLEDZIĆ",
  visitProfile:"WIZYTA PROFIL",
  itemDetails:"SZCZEGÓŁY PRZEDMIOTU",
  detailsPicture:"Szczegóły zdjęcia",
  recommendedFromThisSupplier:"Zaleca się od tego dostawcy",
  recommendedFromOtherSupplier:"Zaleca się od innych dostawców",
  sendEnquiry:"wyślij zapytanie",
  chatNow:"czat teraz",
  sendEnquiry:"wyślij zapytanie",
  attachPhotos:"Dołącz zdjęcia",
  recommendOtherSuppliers:"Polecamy inne pasujące dostawców jeśli to dostawca nie kontakt w ciągu 24 godzin.",
  agreeToShareContactInfo:"Wyrażam zgodę na udostępnienie moich danych kontaktowych w swoim profilu nabywcy z dostawcą.",
  send:"WYSŁAĆ",
  accounts:"RACHUNKI",
  manageOrders:"zarządzanie zamówieniami",
  favourites:"Ulubione",
  quotations:"Twoje notowania",
  buyingRequest:"Kupno Zapytanie",
  profileDetails:"szczegóły profilu",
  settings:"Ustawienia",
  aboutUs:"O nas",
  TC:"Zasady i Warunki",
  privacyPolicy:"Polityka prywatności",
  contactUs:"Skontaktuj się z nami",
  profileDetailsTitle:"SZCZEGÓŁY PROFILU",
  firstName:"Imię",
  lastName:"Nazwisko",
  contactNumber:"Numer kontaktowy",
  changePassword:"ZMIEŃ HASŁO",
  updateDetails:"Aktualizuj dane",
  otp:"OTP",
  newPassword:"nowe hasło",
  save:"ZAPISAĆ",
  language:"Język",
  notifications:"Powiadomienia",
  languageTitle:"JĘZYK",
  companyName:"Nazwa firmy",
  location:"Lokalizacja",
  logout:"WYLOGUJ",
  welcome:"Witamy na Brown Eagle",
  loginOrSignup:"Zaloguj się lub zarejestruj się lubić",
  continueWith:"KONTYNUOWAĆ",
  fb:"FACEBOOK",
  google:"GOOGLE",
  enterEmail:"Wprowadź swój adres e-mail",
  emailSent:"E-mail z potwierdzeniem został wysłany do skrzynki pocztowej",
  checkEmail:"Proszę sprawdzić email.",
  resendEmail:"Wyślij email ponownie",
  notReceiveEmail:"Problem po otrzymaniu e-maila?",
  clickHere:"Kliknij tutaj",
  manageProducts:"zarządzania produktami",
  manageProductsTitle:"zarządzania produktami",
  manageBusiness:"zarządzanie Biznes",
  allProducts:"Wszystkie produkty",
  approvedProducts:"zatwierdzone produkty",
  approvedProductsTitle:"zatwierdzonych produktów",
  approvalPending:"KONTA",
  rejectedProducts:"Produkty odrzucone",
  rejectedProductsTitle:"produkty odrzucone",
  addNewProduct:"DODAJ nowy produkt",
  allProductsTitle:"WSZYSTKIE PRODUKTY",
  productNameCannotEmpty:"Nazwa produktu nie może być pusty",
  ok:"dobrze",
  pleaseEnterKeyword:"Proszę podać co najmniej jedno słowo o produkcie",
  productCatCannotEmpty:"Kategoria produktu nie może być pusty",
  productSubCatCannotEmpty:"kategoria sub Produkt nie może być pusty",
  addProductDescription:"Dodaj opis produktu",
  productQualityCannotBeEmpty:"Minimalna ilość produktu nie może być pusty",
  addProductPrice:"Dodać cenę produktu",
  basicInformation:"Podstawowe informacje",
  productName:"Nazwa produktu",
  productKeywords:"Słowa kluczowe dla tego produktu",
  catInformation:"Kategoria Informacja",
  category:"Kategoria",
  searchCat:"Kategorie wyszukiwania",
  subCat:"Podkategoria",
  productDetailsInformation:"Szczegóły Informacje o produkcie",
  productPhoto:"Produkt Photo / Video",
  productDescription:"Opis produktu",
  requirement:"Wymaganie",
  minQuality:"Minimalna ilość (ex - 10)",
  productPrice:"Cena produktu",
  submit:"ZATWIERDŹ",
  addProductTitle:"Dodaj produkt",
  cancel:"anulować",
  fromCamera:"z aparatu",
  fromLibrary:"z biblioteki",
  apparel:"Strój",
  transportation:"Auto & Transport",
  electronics:"Elektronika",
  machinery:"Maszyneria",
  gifts:"prezenty",
  homeLights:"Dom",
  healthBeauty:"zdrowie i uroda",
  jewelryBags:"Biżuteria",
  electricalEquipment:"Sprzęt elektryczny",
  agriculture:"Rolnictwo i żywność",
  packaging:"Opakowania",
  rawProcessing:"Surowe i przetworzone materiały",
  Apparel:"Strój",
  textile:"Włókiennicze, skórzane",
  fashion:"Akcesoria modowe",
  automobiles:"Samochody i Motocykle",
  Transportation:"Transport",
  computer:"Komputery",
  consumerElectronics:"Elektroniki użytkowej",
  homeAppliances:"Urządzenia domowe",
  security:"Bezpieczeństwo i ochrona",
  hardware:"Hardware & Tools",
  instruments:"Analiza i pomiar Instruments",
  Machinery:"Maszyneria",
  mechanicalParts:"Części mechaniczne i Wykonanie usługi",
  giftsCrafts:"Upominki, ozdoby",
  sportsEnternainment:"Sport i rozrywka",
  toys:"Zabawki i Hobby",
  construction:"Budownictwo i nieruchomości",
  lights:"Lights & Lighting",
  homeGarden:"Dom i ogród",
  furniture:"Meble",
  healthMedical:"Zdrowie i medycyna",
  beautyCare:"Kosmetyki pielęgnacyjne",
  luggageBags:"Bagaż",
  timePieces:"Zegarki",
  shoesAccessories:"Buty i akcesoria",
  electricalSuppliers:"Sprzęt elektryczny",
  elctronicComponents:"Elektroniczne części składowe i systemy",
  telecommunications:"Telekomunikacja",
  agriculture:"Rolnictwo",
  foodBeverage:"jedzenie i napoje",
  packagingPrinting:"Poligraficzne i pakowanie",
  schoolSuppliers:"Biurowe i szkolne",
  serviceEquipment:"serwis sprzętu",
  mineralsMetallurgy:"Minerały i metalurgia",
  chemicals:"Środki chemiczne",
  rubberPlastic:"Guma",
  energy:"Energia",
  environment:"Środowisko",
  youHaveNotAddedProduct:"Nie dodano jeszcze żadnego produktu.",
  pendingProducts:"PRODUKTY oczekujące",
  areYouSure:"Jesteś pewny?",
  yes:"tak",
  update:"AKTUALIZACJA",
  notApproved:"Żaden z produktów został zatwierdzony",
  noProductsFound:"Nie znaleziono produktów",
  clickToEdit:"Kliknij aby edytowac",
  haveAnyQues:"Jeśli masz jakiekolwiek pytania dotyczące niniejszych Warunków",
  contact:"KONTAKT",
  address:"BROWN EAGLE INC. \ N1000 N West Street \ nSuite 1200 \ nWilmington",
  registeredAddress:"Zarejestrowany adres",
  Address:"Adres",
  city:"Miasto",
  state:"Stan",
  zipCode:"Kod pocztowy",
  country:"Kraj",
  operationalAddress:"Adres operacyjny",
  companyInfo:"informacje o firmie",
  website:"Strona WWW (np: http://www.example.com)",
  established:"Ustanowiony",
  employeeCount:"hrabia pracownik",
  description:"Opis Firmy",
  emailNotVerified:"EMAIL niezweryfikowany",
  verifyNow:"Kliknij Sprawdź, aby zweryfikować swoje konto BrownEagle",
  later:"Później",
  mainProducts:"Główne Produkty",
  add:"DODAJ",
  keywordsEx:"(Np kluczowe1",
  settingsTitle:"USTAWIENIA",
  TCTtile:"ZASADY I WARUNKI",
  contactUsTitle:"SKONTAKTUJ SIĘ Z NAMI",
  profileNotVerified:"PROFIL WERYFIKACJI KONTA",
  ok:"dobrze",
  sameAsRegisteredAddress:"Taki sam jak adres siedziby",
  passwordResetMsg:"Aby zresetować hasło",
  account:"Konto",
  payment:"Zapłata",
  sales:"Obroty",
  support:"Wsparcie",
  others:"Pozostałe",
  chooseDepartment:"Wybierz Department",
  message:"Wiadomość...",
  rfqTitle:"SKUP WNIOSEK",
  searchRfq:"Search zapytanie ofertowe",
  rfqDetailsTitle:"RFQ SZCZEGÓŁY",
  quantityRequired:"Wymagana ilosć",
  availability:"Dostępność",
  datePosted:"Data opublikowania",
  detailedDescription:"szczegółowy opis",
  quoteNow:"kosztorysu",
  emailAlreadyExists:"email już istnieje",
  enterValidEmail:"Proszę wpisać aktualny adres e-mail",
  passwordCannotBeEmpty:"Hasło nie może być puste",
  onlyBuyersCanLoggedIn:"Tylko kupujący mogą zalogowany.",
  enterValidName:"Proszę podać poprawny imię",
  enterValidLastName:"Proszę wpisz właściwe nazwisko",
  enterValidContact:"Proszę podać poprawny numer kontaktowy",
  passwordLengthError:"Hasło nie może być mniejsza niż 6 znaków",
  passwordNotMatched:"Hasła didnot dopasowane",
  noUserRegistered:"Nie zarejestrowany adres e-mail użytkownika",
  profileUpdatedSuccessfully:"Szczegóły profilu aktualizowane są z powodzeniem",
  passwordUpdatedSuccessfully:"Hasło zostało zmienione",
  enterValidCompanyName:"Proszę podać poprawną nazwę firmy",
  countryOrRegion:"Kraj / Region",
  onlySellersCanLoggedin:"Tylko sprzedający Brązowy Orzeł może zalogowany.",
  fetchingLocation:"Pobieranie lokalizacja ...",
  noCategoriesFound:"Nie znaleziono kategorii",
  noSubcategoriesFound:"Nie znaleziono podkategorie",
  addressCannotBeEmpty:"Zarejestrowany adres nie może być pusty",
  operationalAddressCannotBeEmpty:"adres operacyjny nie może być pusty",
  websiteCannotBeEmpty:"Strona internetowa nie może być pusty",
  establishedCannotBeEmpty:"Firma założona rok nie może być pusty",
  employeeCountCannotBeEmpty:"Ilość pracownik nie może być pusty",
  imageExceedsAlert:"można przesyłać do połowy 6 obrazów.",
  quantity:"Quant",
  pieces:"jednostki",
  piece:"jednostka",
  noRfqFound:"Nie znaleziono zapytania ofertowe",
  subCategory:"Podkategoria",
  unitPrice:"Cena jednostkowa",
  verified:"Zweryfikowane",
  title:"Tytuł",
  delete:"KASOWAĆ",
  categoryTitle:"KATEGORIE",
  sendQuotationsTitle:"WYŚLIJ WYCENA",
  enterQuantity:"Wpisz ilość",
  enterUnitPrice:"Podaj cenę jednostkową",
  productDetail:"Szczegóły Produktu",
  sendProposal:"Wyślij wniosek",
  deliveryTime:"Czas dostawy",
  enterDeliveryTime:"Wprowadź czas dostawy (w dniach)",
  quotationsTitle:"Moje oferty cenowe",
  searchQuotations:"Szukaj notowania",
  QUOTATIONS:"NOTOWANIA",
  status:"Status",
  all:"Wszystko",
  open:"otwarty",
  rejected:"odrzucony",
  closed:"Zamknięte",
  sortBy:"Sortuj według",
  startDate:"Data rozpoczęcia",
  endDate:"Data końcowa",
  quotationDetalisTitle:"WYCENA DANE",
  shopBy:"Kupować przez",
  enterTitle:"Wprowadź tytuł",
  minQuantity:"Minimalna ilość",
  quotedPrice:"Cena cytowany",
  estimatedDeliveryTime:"Przewidywany czas dostarczenia",
  enterMinQuantity:"Wprowadź minimalną quntity",
  enterEtimatedDeliveryTime:"Wpisz szacowany czas dostawy",
  coverLetter:"List motywacyjny",
  enterCoverLetter:"Wpisz list motywacyjny",
  pleaseEnterTitle:"Podaj tytuł",
  pleaseEnterMinQuantity:"Proszę podać ilość minimalną",
  pleaseEnterQuotedPrice:"Podaj cenę cytowany",
  pleaseEnterEstimatedDeliveryTime:"Proszę podać szacunkowy czas dostawy",
  pleaseEnterCoverLetter:"Prosimy o przesłanie listu motywacyjnego",
  quottionSubmittedSuccessfully:"Twój cytat został przesłany pomyślnie",
  noQuotationsFound:"nie znaleziono żadnych cytatów",
  membershipPlan:"Plan uaktualnień",
  membershipPlanTitle:"członków PLAN",
  expandBusiness:"Załóżmy Rozwiń swoją firmę dzięki której można uzyskać natychmiastowe zaufanie kupujących",
  chooseMembershipPackage:"Wybierz pakiet Membership",
  noPackagesAtYourLocation:"Brak planów na swoim miejscu",
  package:"Pakiet",
  storage:"Przechowywanie miesięcznie",
  nextRenewal:"Następny Odnowienie",
  expireOn:"Wygasa z dniem",
  unSubscribePlan:"Wyrejestrowanie Plan",
  subscribePlan:"Zapisz się plan",
  subscribeConfirm:"Czy na pewno chcesz subskrybować plan?",
  unSubscribeConfirm:"Czy na pewno chcesz zrezygnować z planu?",
  subscriptionFailed:"Nie udało się Wypisz planu",
  productListing:"Razem Lista produktów",
  detailsTitle:"DETALE",
  packageCost:"Koszt pakietu",
  service:"Usługa",
  serviceType:"Rodzaj usługi",
  serviceCost:"Koszt usługi",
  upgradeNow:"ULEPSZ TERAZ",
  upload:"Przekazać plik",
  video:"Wideo",
  myCertificates:"My Certyfikaty",
  myCertificatesTitle:"moimi certyfikatami",
  noCertificatesUploaded:"Nie Certyfikaty Wgrany",
  addCertificate:"CERTYFIKAT ADD",
  viewCertificateTitle:"WIDOK",
  clickToView:"Kliknij, aby zobaczyć",
  certificateTitle:"CERTYFIKAT TYTUŁ",
  somethingWentWrong:"Coś poszło nie tak. Spróbuj ponownie później",
  titleCannotBeEmpty:"Tytuł nie może być pusty",
  certificateUploadedSuccessfully:"Twój certyfikat został pomyślnie przesłany",
  myVideosTitle:"okładki",
  myVideos:"okładki",
  noVideosUploaded:"Nie znaleziono pokrywa wideo",
  addVideo:"DODAJ TERAZ",
  canUploadOnlyOneVideo:"Możesz przesłać tylko 1 film",
  brownEagleWillCharge:"Brązowy Eagle obciąży",
  commissionForThisCategory:"prowizji dla tej kategorii",
  termsAndConditionsApplied:"Warunki i Stosowanej",
  noTermsFound:"Regulamin nie są stosowane.",
  cannotAddThisCategory:"Nie można dodać do tej kategorii, ponieważ nie zawiera jeszcze żadnych podkategorie. Proszę dodać inne kategorie.",
  allOrders:"Wszystko",
  yearlyRfqLimit:"Roczne ograniczenie zapytania ofertowe",
  contactPersonDetails:"Osoba kontaktowa Szczegóły",
  name:"Imię",
  contactPersonCannotBeEmpty:"Osoba kontaktowa szczegóły nie może być pusty",
  quickDetails:"Szybkie Szczegóły",
  label:"Etykieta",
  value:"Wartość",
  addMore:"Dodaj więcej",
  pending:"w oczekiwaniu",
  profileVerification:"Profil Weryfikacja",
  profileApproval:"profil Zatwierdzenie",
  confirmed:"potwierdzonych zamówień",
  shippedOrders:"Zamówienia dostarczane",
  deliveredOrders:"Zamówienia dostarczane",
  rejectedOrders:"odrzucone Zlecenia",
  cancelledOrders:"anulowanie zamówienia",
  noOrdersFound:"nie znaleziono żadnych zleceń",
  checkout:"SPRAWDZIĆ",
  orderShippedd:"Zamówienie wysłane",
  confirmedd:"Zatwardziały",
  cancelled:"Anulowany",
  paymentSuccessfull:"Udane PŁATNOŚCI",
  allOrdersTitle:"WSZYSTKIE ZAMÓWIENIA",
  from:"z",
  minOrder:"Min. Zamówienie",
  allOrders:"Wszystko",
  waitingForContractDraft:"Oczekiwanie na projekcie umowy",
  waitingForOrderConfirmation:"Oczekiwanie na potwierdzeniu zamówienia",
  waitingForPayment:"czekać na wypłatę",
  waitingForPaymentConfirmation:"Oczekiwanie na potwierdzenie płatności",
  waitingForShipment:"Oczekiwanie na przesyłkę",
  waitingForDeliveryConfirmation:"Oczekiwanie na potwierdzenie dostawy",
  orderCancelRequested:"Zamówienie anulowane żądanie",
  disputeOrRefund:"Spór / Zwrot",
  completed:"Zakończony",
  closed:"Zamknięte",
  waitingForSupplier:"Oczekiwanie na dostawcę aby potwierdzić",
  waitingForPayment:"czekać na wypłatę",
  shipped:"Wysłane",
  delivered:"dostarczane",
  productStatus:"Stan produktu",
  chat:"CZAT",
  supplierAndProductInformation:"Dostawca i informacje o produkcie",
  total:"Całkowity",
  orderDetails:"Szczegóły zamówienia",
  orderNumber:"Numer zamówienia",
  orderSubmitted:"Złożone zamówienie",
  cancelOrder:"ANULOWAĆ",
  track:"TOR",
  trackOrderTitle:"Monitoruj zamówienie",
  shippingAddress:"adres wysyłki",
  landmark:"Punkt orientacyjny",
  buyerAndProductInformation:"Kupujący i informacje o produkcie",
  reject:"ODRZUCAĆ",
  accept:"ZAAKCEPTOWAĆ",
  rejectOrder:"odrzucenia zlecenia",
  acceptOrder:"ACCEPT ORDER",
  orderDetailsTitle:"SZCZEGÓŁY ZAMÓWIENIA",
  track:"TOR",
  key:"Klawisz",
  quickDetailsEx:"(Ex- kolor: czarny)",
  customerReviews:"Opinie klientów",
  customerReview:"recenzję",
  allReviewsTitle:"WSZYSTKIE OPINIE",
  productPreview:"Produkt Podgląd",
  show:"POKAZAĆ",
  productPreviewTitle:"PRZEGLĄD PRODUKTU",
  supplierProfile:"Dostawca profilu",
  view:"Widok",
  contactPerson:"Osoba kontaktowa",
  ratingsReviews:"Oceny i recenzje",
  recentlyAddedReviews:"Ostatnio dodane opinie",
  thisProductHasNoReview:"Przepraszam",
  days:"dni",
  perQuantity:"za ilość",
  rfqDetails:"Zapytanie ofertowe Szczegóły -",
  myQuotation:"mój cytat",
  inDays:"W dniach",
  notAdded:"Nie dodany",
  viewTermsConditions:"Zobacz Regulamin",
  by:"przez",
  paymentSuccessfull:"Udane PŁATNOŚCI",
  planUpgradedSuccessfully:"Uaktualnieniu planu",
  pleaseWaitPaymentMsg:"Poczekaj jesteśmy przetwarzania żądania ...",
  activePlan:"aktywny Plan",
  productUsed:"Produkt używany",
  storageUsed:"Przechowywanie używany",
  storageRemaining:"Pozostała bagażu",
  rfqUsed:"RFQ używany",
  rfqRemaining:"zapytanie ofertowe pozostały",
  noActivePlan:"Nie kupiłeś żadnego planu członkostwa. Wybierz pakiet członkowski, który pomaga uzyskać natychmiastowe zaufanie kupujących",
  sellerShare:"Sprzedawca Share",
  commission:"Komisja",
  productDimensions:"wymiary produktu",
  weight:"Waga (w gramach)",
  width:"Szerokość (w calach)",
  height:"Wysokość w calach)",
  depth:"Głębokość (w calach)",
  pleaseEnterDimensions:"Należy dodać wymiary produktu",
  myReferences:"Moi Referencje",
  noReferencesAdded:"Brak odniesienia dodany",
  addReferences:"LITERATURA ADD",
  clientInformation:"Informacja klientów",
  shortNote:"Napisz krótką notatkę",
  yourReferenceCreatedSuccessfully:"Twój wniosek został pomyślnie utworzony",
  unableToOpen:"NIEMOŻLIWE DO OTWARCIA",
  urlIsNotCorrect:"URL nie jest poprawna",
  yourReferenceSavedSuccessfully:"Twój wniosek został zapisany pomyślnie",
  orderPlaced:"Twoja płatność została wykonana pomyślnie",
  shippingOrders:"Wysyłka zamówień",
  payments:"Płatności",
  personalDetails:"Dane osobowe",
  companyDetails:"Szczegóły firmy",
  kycSubmitConfirm:"Czy na pewno chcesz przesłać formularz KYC?",
  kycSubmittedSuccessfully:"Twój KYC została przesłana pomyślnie. Zostaniesz powiadomiony, gdy będziemy przetwarzać swój status",
  packageDimensions:"Wymiary opakowania",
  length:"Długość (w calach)",
  units:"Jednostki (w liczbie)",
  shippingOptions:"Sposób wysyłki",
  shippingCharges:"Koszty przesyłki",
  listPrice:"Cennik",
  grandTotal:"Łączna suma",
  productTermsConditions:"Warunki produkcie",
  enterTermsConditions:"Wprowadź warunki"
}
