export const es={
  login:"INICIAR SESIÓN",
  register:"REGISTRO",
  username:"Nombre de usuario",
  email:"e-mail",
  mobile:"móvil",
  password:"contraseña",
  confirmPassword:"Confirmar contraseña",
  signup:"REGISTRARSE",
  otpMessage:"Ingrese 4 dígitos que OTP siente en su dispositivo móvil",
  enterOTP:"Ingrese OTP",
  verify:"VERIFICAR",
  resendOTP:"Reenviar Verificación OTP",
  emailOrusername:"Email/Usuario",
  continueWithFb:"CONTINUAR CON FACEBOOK",
  continueWithGoogle:"CONTINÚE CON GOOGLE",
  forgotPassword:"OLVIDÓ LA CONTRASEÑA?",
  enterMobile:"Ingrese su número de teléfono registrado",
  verify:"VERIFICAR",
  trendingProducts:"PRODUCTOS TOP TRENDING",
  lightEquipmentTools:"HERRAMIENTAS PARA EQUIPO DE LUZ",
  foodProducts:"ALIMENTOS Y PRODUCTOS AL POR MENOR",
  latestProducts:"ÚLTIMOS PRODUCTOS",
  recommendedProducts:"PRODUCTOS RECOMENDADOS",
  topRatedProducts:"LOS PRODUCTOS TOP CLASIFICADOS",
  heavyEquipmentTools:"HERRAMIENTAS PARA EQUIPOS PESADOS",
  products:"PRODUCTOS",
  suppliers:"PROVEEDORES",
  searchProducts:"Buscar productos",
  searchSuppliers:"Proveedores de búsqueda",
  recentSearches:"Búsquedas recientes",
  popularSearches:"Búsquedas Populares",
  results:"resultados",
  contact:"Contactar",
  productDetails:"DETALLES DEL PRODUCTO",
  companyProfile:"Perfil de la empresa",
  follow:"SIGA",
  visitProfile:"VISITA EL PERFIL",
  itemDetails:"DETALLES DEL ARTÍCULO",
  detailsPicture:"Cuadro de detalles",
  recommendedFromThisSupplier:"Recomendado de este proveedor",
  recommendedFromOtherSupplier:"Recomendado de otro proveedores",
  sendEnquiry:"ENVIAR CONSULTA",
  chatNow:"CAT AHORA",
  sendEnquiry:"ENVIAR CONSULTA",
  attachPhotos:"Adjuntar fotos",
  recommendOtherSuppliers:"Recomiende a otros proveedores que coincidan si este proveedor no se pone en contacto conmigo dentro de las 24 horas.",
  agreeToShareContactInfo:"Acepto compartir mi información.",
  send:"ENVIAR",
  accounts:"CUENTAS",
  manageOrders:"Administrar pedidos",
  favourites:"favoritos",
  quotations:"Tus citas",
  buyingRequest:"Solicitud de compra",
  profileDetails:"Detalles del perfil",
  settings:"ajustes",
  aboutUs:"Sobre nosotros",
  TC:"Términos y condiciones",
  privacyPolicy:"Política de privacidad",
  contactUs:"Contáctanos",
  profileDetailsTitle:"DETALLES DEL PERFIL",
  firstName:"Nombre",
  lastName:"Apellido",
  contactNumber:"Número de contacto",
  changePassword:"CAMBIAR CONTRASEÑA",
  updateDetails:"ACTUALIZAR DETALLES",
  otp:"OTP",
  newPassword:"Nueva contraseña",
  save:"GUARDAR",
  language:"Guardar",
  notifications:"Notificaciones",
  languageTitle:"IDIOMA",
  companyName:"Nombre de la compañía",
  location:"Arrendamiento",
  logout:'CERRAR SESIÓN',
  welcome:'Bienvenido a Brown Eagle',
  loginOrSignup:'Iniciar sesión o registrarse para recibir me gusta, recopilar y gestionar pedidos',
  continueWith:'CONTINUA CON',
  fb:'FACEBOOK',
  google:'GOOGLE',
  enterEmail:'Por favor, introduzca su dirección de correo electrónico',
  emailSent:'Se ha enviado un correo electrónico de confirmación a su casilla de correo',
  checkEmail:'Por favor revise su correo electrónico',
  resendEmail:'Reenviar email',
  notReceiveEmail:'Hai problemi a ricevere email',
  clickHere:'Haga clic aquí',
  manageProducts:'Administrar producto',
  manageProductsTitle:'Administrar producto',
  manageBusiness:'Administrar negocios',
  allProducts:'Todos los productos',
  approvedProducts:'Productos aprobados',
  approvedProductsTitle:'Productos aprobados',
  approvalPending:'Aprobación pendiente',
  rejectedProducts:'Productos rechazados',
  rejectedProductsTitle:'Productos rechazados',
  addNewProduct:'AGREGUE UN NUEVO PRODUCTO',
  allProductsTitle:'TODOS LOS PRODUCTOS',
  productNameCannotEmpty:'El nombre del producto no puede estar vacío',
  ok:'DE ACUERDO',
  pleaseEnterKeyword:'Por favor ingrese al menos una palabra clave de producto',
  productCatCannotEmpty:'La categoría del producto no puede estar vacía',
  productSubCatCannotEmpty:'La subcategoría de productos no puede estar vacía',
  addProductDescription:'Añadir una descripción del producto',
  productQualityCannotBeEmpty:'La cantidad mínima del producto no puede estar vacía',
  addProductPrice:'Añadir un precio del producto',
  basicInformation:'Información básica',
  productName:'nombre del producto',
  productKeywords:'Palabras clave del producto',
  catInformation:'Información de la categoría',
  category:'Categoría',
  searchCat:'Buscar Categorías',
  subCat:'Subcategoría',
  productDetailsInformation:'Información de detalles del producto',
  productPhoto:'Foto del producto / vídeo',
  productDescription:'Descripción del producto',
  requirement:'Requisito',
  minQuality:'Cantidad mínima (ex - 10)',
  productPrice:'Precio del producto',
  submit:'ENVIAR',
  addProductTitle:'AGREGAR PRODUCTO',
  cancel:'Cancelar',
  fromCamera:'Desde la cámara',
  fromLibrary:'De la biblioteca',
  rel:'Ropa, textiles y accesorios',
  transportation:'Auto y Transporte',
  electroappanics:'Electrónica',
  machinery:'Maquinaria, Hardware y Herramientas',
  gifts:'Regalos, deportes y pasatiempos',
  homeLights:'Hogar, luces y construcción',
  healthBeauty:'Salud y Belleza',
  jewelryBags:'Joyas, bolsos y zapatos',
  electricalEquipment:'Equipo eléctrico',
  agriculture:'Agricultura y Alimentos',
  packaging:'Embalaje, publicidad y oficina',
  rawProcessing:'Materiales crudos y procesados',
  Apparel:'Vestir',
  textile:'Textil y productos de cuero',
  fashion:'Accesorios de moda',
  automobiles:'automoviles y motocicletas',
  Transportation:'Transporte',
  computer:'Ordenadores',
  consumerElectronics:'Electrónica de consumo',
  homeAppliances:'Electrodomésticos',
  security:'Protección de seguridad',
  hardware:'Hardware y herramientas',
  instruments:'Instrumentos de medición y análisis',
  Machinery:'Maquinaria',
  mechanicalParts:'Servicio de piezas mecánicas y fabricación',
  giftsCrafts:'Regalos y artesanías',
  sportsEnternainment:'Deportes y Entretenimiento',
  toys:'Juguetes y pasatiempos',
  construction:'Construcción y Bienes Raíces',
  lights:'Luces e iluminación',
  homeGarden:'Hogar y jardín',
  furniture:'muebles',
  healthMedical:'Salud y Medicina',
  beautyCare:'Belleza y cuidado personal',
  luggageBags:'Equipaje, bolsos y estuches',
  timePieces:'Relojes, joyas, gafas',
  shoesAccessories:'Zapatos y accesorios',
  electricalSuppliers:'Equipo eléctrico y suministros',
  elctronicComponents:'Componentes electrónicos y suministros',
  telecommunications:'Telecomunicaciones',
  agriculture:'Agricultura',
  foodBeverage:'Comida y bebida',
  packagingPrinting:'Empaquetado e impresión',
  schoolSuppliers:'Oficina y útiles escolares',
  serviceEquipment:'Equipo de servicio',
  mineralsMetallurgy:'Minerales y Metalurgia',
  chemicals:'Chemicals',
  rubberPlastic:'Caucho y Plásticos',
  energy:'energía',
  environment:'medio ambiente',
  youHaveNotAddedProduct:'No ha agregado ningún producto todavía.',
  pendingProducts:'PRODUCTOS PENDIENTES',
  areYouSure:'¿Estás seguro?',
  yes:'Sí',
  update:'ACTUALIZAR',
  notApproved:'Ninguno de sus productos ha sido aprobado',
  noProductsFound:'No se encontraron productos',
  clickToEdit:'Haz click para editar',
  haveAnyQues:'Si tiene alguna pregunta sobre estos Términos, contáctenos.',
  contact:'CONTACTO',
  address:'BROWN EAGLE INC.\n1000 N West Street\nSuite 1200\nWilmington, DE 19801\nNúmero de teléfono: 302-295-3816\nNúmero de fax: 302-295-4801',
  registeredAddress:'Dirección registrada',
  Address:'Dirección',
  city:'Ciudad',
  state:'CAP',
  zipCode:'Código postal',
  country:'País',
  operationalAddress:'Dirección operacional',
  companyInfo:'Información de la compañía',
  website:'Sitio web(ex: http://www.example.com)',
  established:'Establecido',
  employeeCount:'número de empleados',
  description:'Descripción de la compañía',
  emailNotVerified:'EMAIL NOT VERIFIED',
  verifyNow:'Haga clic en VERIFICAR para verificar su cuenta BrownEagle',
  later:'Luego',
  mainProducts:'Productos principales',
  add:'AÑADIR',
  keywordsEx:'(por ejemplo: Keyword1, Keyword2, Keyword3)',
  settingsTitle:'AJUSTES',
  TCTtile:'TÉRMINOS Y CONDICIONES',
  contactUsTitle:'CONTÁCTENOS',
  profileNotVerified:'VERIFICACIÓN DEL PERFIL PENDIENTE',
  ok:'DE ACUERDO',
  sameAsRegisteredAddress:"Igual que la dirección registrada",
  passwordResetMsg:'Para restablecer su contraseña, se ha enviado un correo electrónico a su casilla de correo',
  account:'Account',
  payment:'pago',
  sales:'venta',
  support:'apoyo',
  others:'otros',
  chooseDepartment:'Elegir departamento',
  message:'Mensaje ...',
  rfqTitle:'SOLICITUD DE COMPRA',
  searchRfq:'Buscar RFQ',
  rfqDetailsTitle:'DETALLES DE LA RFQ',
  quantityRequired:'Cantidad requerida',
  availability:'disponibilidad',
  datePosted:'Date Posted',
  detailedDescription:'Descripción detallada',
  quoteNow:'PREVENTIVO ORA',
  emailAlreadyExists:'El correo electrónico ya existe',
  enterValidEmail:"Por favor ingrese una dirección de correo electrónico válida",
  passwordCannotBeEmpty:'La contraseña no puede estar vacía',
  onlyBuyersCanLoggedIn:'Solo los compradores pueden iniciar sesión.',
  enterValidName:'Por favor ingrese un nombre de pila válido',
  enterValidLastName:'Por favor ingrese un apellido válido',
  enterValidContact:'Por favor ingrese un número de contacto válido',
  passwordLengthError:'La contraseña no puede tener menos de 6 caracteres',
  passwordNotMatched:'Tus contraseñas no coincidieron',
  noUserRegistered:'Ningún usuario registrado con la dirección de correo electrónico',
  profileUpdatedSuccessfully:'Detalles del perfil actualizados con éxito',
  passwordUpdatedSuccessfully:'Contraseña actualizada con éxito',
  enterValidCompanyName:'Por favor ingrese un nombre de compañía válido',
  countryOrRegion:'País/Región',
  onlySellersCanLoggedin:'Solo los vendedores de Brown Eagle pueden iniciar sesión.',
  fetchingLocation:'Obteniendo alquiler ...',
  noCategoriesFound:'No se encontraron categorías',
  noSubcategoriesFound:'No se encontraron subcategorías',
  addressCannotBeEmpty:'La dirección no puede estar vacía',
  operationalAddressCannotBeEmpty:'La dirección operacional no puede estar vacía',
  websiteCannotBeEmpty:'El sitio web no puede estar vacío',
  establishedCannotBeEmpty:'Empresa establecida año no puede estar vacía',
  employeeCountCannotBeEmpty:'El recuento de empleados no puede estar vacío',
  imageExceedsAlert:'Puedes subir hasta 6 imágenes.',
  quantity:'inventario',
  pieces:'unidades',
  piece:'unidad',
  noRfqFound:'No RFQs encontrado',
  subCategory:'Subcategoría',
  unitPrice:'Precio unitario',
  verified:'verificado',
  title:'Título',
  delete:'DELETE',
  categoryTitle:'CATEGORÍAS',
  sendQuotationsTitle:'ENVIAR PRESUPUESTO',
  enterQuantity:'Ingrese una cantidad',
  enterUnitPrice:'Ingrese un precio unitario',
  productDetail:'Detalles del producto',
  sendProposal:'Enviar una propuesta',
  deliveryTime:'Tiempo de entrega',
  enterDeliveryTime:'Ingrese un tiempo de entrega (en días)',
  quotationsTitle:'MIS COTIZACIONES',
  searchQuotations:'Citas de búsqueda',
  QUOTATIONS:"citas",
  status:'estatus',
  all:'todos',
  open:'abierto',
  rejected:'rechazado',
  closed:'cerrado',
  sortBy:'Ordenar por',
  startDate:'Fecha de inicio',
  endDate:'Fecha de finalización',
  quotationDetalisTitle:'DETALLES DE COTIZACIÓN',
  shopBy:"Comprar por",
  enterTitle:'Ingrese un Título',
  minQuantity:'Cantidad mínima',
  quotedPrice:'Precio cotizado',
  estimatedDeliveryTime:'Tiempo estimado de entrega',
  enterMinQuantity:'Ingrese la cantidad mínima',
  enterEtimatedDeliveryTime:'Ingrese el tiempo de entrega estimado',
  coverLetter:'Carta de presentación',
  enterCoverLetter:'Ingrese una carta de presentación',
  pleaseEnterTitle:'Por favor ingrese un título',
  pleaseEnterMinQuantity:'Por favor ingrese una cantidad mínima',
  pleaseEnterQuotedPrice:'Por favor ingrese un precio cotizado',
  pleaseEnterEstimatedDeliveryTime:'Ingrese el tiempo de entrega estimado',
  pleaseEnterCoverLetter:'Por favor envíe una carta de presentación',
  quottionSubmittedSuccessfully:'Su cotización ha sido enviada exitosamente',
  noQuotationsFound:'No se encontraron citas',
  membershipPlan:'Plan de actualización',
  membershipPlanTitle:'PLAN DE MEMBRESÍA',
  expandBusiness:"Vamos Expanda su negocio que lo ayuda a obtener la confianza inmediata de los compradores",
  chooseMembershipPackage:'Elija un paquete de membresía',
  noPackagesAtYourLocation:'No hay planes en tu ubicación',
  package:'paquete',
  storage:'Almacenamiento por mes',
  nextRenewal:'Próxima renovación',
  unSubscribePlan:'Plan de baja',
  subscribePlan:'Plan de suscripción',
  subscribeConfirm:"¿Seguro que quieres suscribirte al plan?",
  unSubscribeConfirm:"¿Está seguro de que desea darse de baja del plan?",
  subscriptionFailed:"No se pudo cancelar la suscripción del plan, intente más tarde",
  expireOn:'Vence en',
  productListing:'Total de productos',
  detailsTitle:'DETALLES',
  packageCost:'Costo del paquete',
  service:'servicio',
  serviceType:'Tipo de servicio',
  serviceCost:'Costo del servicio',
  upgradeNow:'ACTUALIZAR AHORA',
  upload:'Subir',
  video:'vídeo',
  myCertificates:'Mis certificados',
  myCertificatesTitle:'MIS CERTIFICADOS',
  noCertificatesUploaded:'No hay certificados cargados',
  addCertificate:'AGREGAR CERTIFICADO',
  viewCertificateTitle:'VISTA',
  clickToView:'Haga clic para ver',
  certificateTitle:'TÍTULO DEL CERTIFICADO',
  somethingWentWrong:'Algo salió mal. Por favor intente de nuevo más tarde',
  titleCannotBeEmpty:"El título no puede estar vacío",
  certificateUploadedSuccessfully:'Su certificado ha sido cargado con éxito',
  myVideosTitle:'CUBIERTA DE VIDEO',
  myVideos:'Cubierta de video',
  noVideosUploaded:'No se encontró un video de portada',
  addVideo:'ADD NOW',
  canUploadOnlyOneVideo:'Puedes subir solo 1 video',
  brownEagleWillCharge:'Brown Eagle cargará',
  commissionForThisCategory:'comisión para esta categoría',
  termsAndConditionsApplied:'Términos y condiciones aplicados',
  noTermsFound:'Los términos y condiciones no se aplican.',
  cannotAddThisCategory:'No puede agregar esta categoría ya que aún no contiene ninguna subcategoría. Por favor agregue otras categorías.',
  allOrders:'Todos',
  yearlyRfqLimit:'Límite anual de RFQs',
  contactPersonDetails:'Detalles de la persona de contacto',
  name:'Nombre',
  contactPersonCannotBeEmpty:'Los detalles de la persona de contacto no pueden estar vacíos',
  quickDetails:'Detalles Rápidos',
  label:'Etiqueta',
  value:'Valor',
  addMore:'Añadir más',
  pending:'Pendiente',
  profileVerification:'Verificación de perfil',
  profileApproval:'Aprobación del perfil',
  confirmed:'Pedidos confirmados',
  shippedOrders:'Pedidos enviados',
  deliveredOrders:'Órdenes entregadas',
  rejectedOrders:'Órdenes rechazadas',
  cancelledOrders:'Órdenes canceladas',
  noOrdersFound:'No se encontraron pedidos',
  checkout:'REVISA',
  orderShippedd:'Orden enviada',
  confirmedd:'Confirmado',
  cancelled:'Cancelado',
  paymentSuccessfull:'PAGO EXITOSO',
  allOrdersTitle:'TODAS LAS ÓRDENES',
  from:'de',
  minOrder:'Min. Orden',
  allOrders:'Todos',
  waitingForContractDraft:'Esperando el borrador del contrato',
  waitingForOrderConfirmation:'Esperando la confirmación del pedido',
  waitingForPayment:'Esperando el pago',
  waitingForPaymentConfirmation:'Esperando confirmación de pago',
  waitingForShipment:'Esperando el envío',
  waitingForDeliveryConfirmation:'Esperando confirmación de entrega',
  orderCancelRequested:'Pedido cancelado solicitado',
  disputeOrRefund:"Disputa/de reembolso",
  completed:'terminado',
  closed:'cerrado',
  waitingForSupplier:'Esperando al proveedor para confirmar el pedido',
  waitingForPayment:'A la espera del pago',
  shipped:'Enviado',
  delivered:'Entregado',
  productStatus:'Estado del producto',
  chat:'CHARLA',
  supplierAndProductInformation:'Información del proveedor y producto',
  total:'Total',
  orderDetails:'Detalles del pedido',
  orderNumber:'Número de orden',
  orderSubmitted:'orden enviada',
  cancelOrder:'CANCELAR',
  track:'PISTA',
  trackOrderTitle:'ORDEN DE PISTA',
  shippingAddress:'Dirección de Envío',
  landmark:'Punto de referencia',
  buyerAndProductInformation:'Información del comprador y del producto',
  reject:'RECHAZAR',
  accept:'ACEPTAR',
  rejectOrder:'ORDEN DE RECHAZO',
  acceptOrder:'ACEPTAR PEDIDO',
  orderDetailsTitle:'DETALLES DE PEDIDO',
  track:'PISTA',
  key:'clave',
  quickDetailsEx:'(por ejemplo, Color: negro)',
  customerReviews:'Reseñas de Clientes',
  customerReview:'Revisión del cliente',
  allReviewsTitle:'TODAS LAS OPINIONES',
  productPreview:'Vista previa del producto',
  show:'DEMOSTRACIÓN',
  productPreviewTitle:'PREVISIÓN DEL PRODUCTO',
  supplierProfile:'Perfil del proveedor',
  view:'Ver',
  contactPerson:'Persona de contacto',
  ratingsReviews:'Calificaciones y comentarios',
  recentlyAddedReviews:'Reseñas recientemente agregadas',
  thisProductHasNoReview:'Lo sentimos, este producto ahora ha sido revisado',
  days:'días',
  perQuantity:'por cantidad',
  rfqDetails:'Detalles de RFQ -',
  myQuotation:"Mi cita",
  inDays:'en días',
  notAdded:'No agregado',
  viewTermsConditions:'Ver los Términos y Condiciones',
  by:'por',
  paymentSuccessfull:'PAGO EXITOSO',
  planUpgradedSuccessfully:'Has actualizado tu plan',
  pleaseWaitPaymentMsg:'Espere mientras procesamos su solicitud ...',
  activePlan:'Plan activo',
  productUsed:'Producto utilizado',
  storageUsed:'Almacenamiento utilizado',
  storageRemaining:'Almacenamiento restante',
  rfqUsed:'RFQ usado',
  rfqRemaining:'RFQ restante',
  noActivePlan:"No ha comprado ningún plan de membresía. Elija un paquete de membresía que lo ayude a obtener la confianza inmediata de los compradores",
  sellerShare:'Vendedor Share',
  commission:'comisión',
  productDimensions:'Dimensiones del producto',
  weight:'Peso(en gramos)',
  width:'Ancho(en pulgadas)',
  height:'Altura(en pulgadas)',
  depth:'Profundidad(en pulgadas)',
  pleaseEnterDimensions:'Please add product dimensions',
  myReferences:'Mis referencias',
  noReferencesAdded:'No se agregaron referencias',
  addReferences:'AÑADIR REFERENCIAS',
  clientInformation:'Información del cliente',
  shortNote:'Escribe una nota corta',
  yourReferenceCreatedSuccessfully:'Tu referencia ha sido creada con éxito',
  unableToOpen:'NO SE PUEDE ABRIR',
  urlIsNotCorrect:'Url no es correcto',
  yourReferenceSavedSuccessfully:'Su referencia se ha guardado con éxito',
  orderPlaced:'Su pago se ha realizado con éxito',
  shippingOrders:'Pedidos de envío',
  payments:'Pagos',
  personalDetails:'Detalles personales',
  companyDetails:'Detalles de la compañía',
  kycSubmitConfirm:'¿Seguro que desea enviar el formulario KYC?',
  kycSubmittedSuccessfully:'Su KYC ha sido enviado exitosamente. Se le notificará una vez que hayamos procesado su estado',
  packageDimensions: 'Dimensiones del paquete',
  length: 'Longitud(en pulgadas)',
  units: 'Unidades(en número)',
  shippingOptions: 'Método de envío',
  shippingCharges: 'Gastos de envio',
  listPrice: 'Precio de lista',
  grandTotal: 'Gran total',
  productTermsConditions: 'Términos y condiciones del producto',
  enterTermsConditions: 'Introduzca los términos y condiciones',

}
