export const tr={
  login:"OTURUM AÇ",
  register:"KAYIT OLMAK",
  username:"Kullanıcı adı",
  email:"E-posta",
  mobile:"seyyar",
  password:"Parola",
  confirmPassword:"Şifreyi Onayla",
  signup:"KAYDOL",
  otpMessage:"4-basamaklı cep telefonuna gönderildi OTP'yi girin",
  enterOTP:"OTP'yi girin",
  verify:"DOĞRULAYIN",
  resendOTP:"Yeniden Gönder Doğrulama OTP",
  emailOrusername:"E-posta / Kullanıcı Adı",
  continueWithFb:"FACEBOOK İLE DEVAM",
  continueWithGoogle:"GOOGLE İLE DEVAM",
  forgotPassword:"PAROLANIZI MI UNUTTUNUZ?",
  enterMobile:"Kayıtlı cep telefonu numarasını girin",
  verify:"DOĞRULAYIN",
  trendingProducts:"En Trend ÜRÜNLERİ",
  lightEquipmentTools:"IŞIK EKİPMAN ARAÇLARI",
  foodProducts:"GIDA & PERAKENDE ÜRÜNLER",
  latestProducts:"EN SON ÜRÜNLER",
  recommendedProducts:"TAVSİYE EDİLEN ÜRÜNLER",
  topRatedProducts:"ÇOK OY ÜRÜNLERİ",
  heavyEquipmentTools:"AĞIR EKİPMAN ARAÇLARI",
  products:"ÜRÜNLER",
  suppliers:"TEDARİKÇİLERİ",
  searchProducts:"ürünleri ara",
  searchSuppliers:"Arama Tedarikçiler",
  recentSearches:"son aramalar",
  popularSearches:"popüler aramalar",
  results:"Sonuçlar",
  contact:"Temas",
  productDetails:"ÜRÜN DETAYLARI",
  companyProfile:"şirket Profili",
  follow:"TAKİP ET",
  visitProfile:"ZİYARETİ PROFİLİ",
  itemDetails:"MADDE DETAYLARI",
  detailsPicture:"Ayrıntılar Resim",
  recommendedFromThisSupplier:"Bu tedarikçiden Tavsiye",
  recommendedFromOtherSupplier:"diğer tedarikçilerden Tavsiye",
  sendEnquiry:"GÖNDER SORGU",
  chatNow:"ŞİMDİ KONUŞ",
  sendEnquiry:"GÖNDER SORGU",
  attachPhotos:"Fotoğraf takın",
  recommendOtherSuppliers:"Bu tedarikçi 24 saat içinde benimle irtibata etmezse başka eşleme tedarikçiler önerilir.",
  agreeToShareContactInfo:"Ben satıcı ile benim Alıcı profilde benim iletişim bilgileri paylaşmayı kabul ediyorum.",
  send:"GÖNDER",
  accounts:"HESAPLAR",
  manageOrders:"Siparişleri yönetin",
  favourites:"Favoriler",
  quotations:"Kişisel Alıntılar",
  buyingRequest:"Alış İsteği",
  profileDetails:"profil detayları",
  settings:"Ayarlar",
  aboutUs:"Hakkımızda",
  TC:"şartlar ve koşullar",
  privacyPolicy:"Gizlilik Politikası",
  contactUs:"Bizimle iletişime geçin",
  profileDetailsTitle:"PROFİL DETAYLARI",
  firstName:"İsim",
  lastName:"Soyadı",
  contactNumber:"İletişim numarası",
  changePassword:"ŞİFRE DEĞİŞTİR",
  updateDetails:"GÜNCELLEME DETAYLARI",
  otp:"OTP",
  newPassword:"Yeni Şifre",
  save:"KAYIT ETMEK",
  language:"Dil",
  notifications:"Bildirimler",
  languageTitle:"DİL",
  companyName:"Şirket Adı",
  location:"yer",
  logout:"ÇIKIŞ YAP",
  welcome:"Kahverengi Eagle hoş geldiniz",
  loginOrSignup:"Giriş veya kayıt sevmeye",
  continueWith:"İLE DEVAM ET",
  fb:"FACEBOOK",
  google:"GOOGLE",
  enterEmail:"lütfen e-mail adresinizi giriniz",
  emailSent:"Bir onay e-posta kutunuza gönderildi",
  checkEmail:"Lütfen emailinizi kontrol edin.",
  resendEmail:"Emaili yeniden gönder",
  notReceiveEmail:"e sorun aldıktan sonra?",
  clickHere:"Buraya TIKLAYIN",
  manageProducts:"Yönet Ürünler",
  manageProductsTitle:"ÜRÜNLERİ YÖNET",
  manageBusiness:"İş yönetme",
  allProducts:"Tüm ürünler",
  approvedProducts:"Onaylı Ürünler",
  approvedProductsTitle:"ONAYLI ÜRÜNLER",
  approvalPending:"Onay Bekliyor",
  rejectedProducts:"Reddedilen Ürünler",
  rejectedProductsTitle:"REDDEDİLDİ ÜRÜNLER",
  addNewProduct:"YENİ ÜRÜN EKLE",
  allProductsTitle:"TÜM ÜRÜNLER",
  productNameCannotEmpty:"Ürün adı boş olamaz",
  ok:"tamam",
  pleaseEnterKeyword:"giriniz En az bir ürün Kelimeler",
  productCatCannotEmpty:"Ürün kategorisi boş olamaz",
  productSubCatCannotEmpty:"Ürün alt kategori boş olamaz",
  addProductDescription:"Bir ürün açıklaması ekleyin",
  productQualityCannotBeEmpty:"Ürün minimum miktar boş olamaz",
  addProductPrice:"Bir ürün fiyat ekle",
  basicInformation:"Temel Bilgiler",
  productName:"Ürün adı",
  productKeywords:"Ürün Anahtar kelimeler",
  catInformation:"Kategori Bilgisi",
  category:"Kategori",
  searchCat:"Arama Kategoriler",
  subCat:"Alt Kategorisi",
  productDetailsInformation:"Ürün Detayları Bilgileri",
  productPhoto:"Ürün Fotoğraf / Video",
  productDescription:"Ürün Açıklaması",
  requirement:"gereklilik",
  minQuality:"En az miktar (örnek - 10)",
  productPrice:"Ürün fiyatı",
  submit:"GÖNDER",
  addProductTitle:"ÜRÜN EKLE",
  cancel:"İptal etmek",
  fromCamera:"Kameradan",
  fromLibrary:"Kitaplıktan",
  apparel:"kıyafet",
  transportation:"Oto ve Ulaşım",
  electronics:"Elektronik",
  machinery:"makinalar",
  gifts:"Hediyeler",
  homeLights:"Ev",
  healthBeauty:"sağlık ve güzellik",
  jewelryBags:"Takı",
  electricalEquipment:"Elektrikli ekipman",
  agriculture:"Tarım ve Gıda",
  packaging:"paketleme",
  rawProcessing:"Ham & İşlenmiş Malzemeler",
  Apparel:"kıyafet",
  textile:"Tekstil ve Deri Ürünleri",
  fashion:"Moda Aksesuarları",
  automobiles:"Otomobiller ve Motosikletler",
  Transportation:"taşımacılık",
  computer:"Bilgisayarlar",
  consumerElectronics:"Tüketici Elektroniği",
  homeAppliances:"Ev Aletleri",
  security:"Güvenlik koruması",
  hardware:"Donanım Araçları",
  instruments:"Ölçüm ve Analiz Cihazları",
  Machinery:"makinalar",
  mechanicalParts:"Mekanik Parça ve İmalat Servisi",
  giftsCrafts:"Hediyeler ve El Sanatları",
  sportsEnternainment:"Spor ve Eğlence",
  toys:"Hobi & Oyuncak",
  construction:"Inşaat ve gayrimenkul",
  lights:"Işıklar ve Işıklandırma",
  homeGarden:"Ev & Bahçe",
  furniture:"Mobilya",
  healthMedical:"Sağlık ve Tıp",
  beautyCare:"Kozmetik ve Kişisel Bakım",
  luggageBags:"Bagaj",
  timePieces:"Saatler",
  shoesAccessories:"Ayakkabı ve Aksesuarları",
  electricalSuppliers:"Elektrik Ekipman ve Malzemeleri",
  elctronicComponents:"Elektronik eşyalar",
  telecommunications:"Telekomünikasyon",
  agriculture:"Tarım",
  foodBeverage:"Yiyecek ve İçecek",
  packagingPrinting:"Packaging & Yazdırma",
  schoolSuppliers:"Ofis ve Okul Malzemeleri",
  serviceEquipment:"servis Ekipmanları",
  mineralsMetallurgy:"Mineraller ve Metalurji",
  chemicals:"Kimyasallar",
  rubberPlastic:"Kauçuk ve Plastik",
  energy:"Enerji",
  environment:"çevre",
  youHaveNotAddedProduct:"Henüz herhangi bir ürünü eklemediniz.",
  pendingProducts:"Askıdaki ÜRÜNLERİ",
  areYouSure:"Emin misiniz?",
  yes:"Evet",
  update:"GÜNCELLEŞTİRME",
  notApproved:"Ürünlerinizin Yok onaylandı",
  noProductsFound:"Hiçbir Ürünleri bulundu",
  clickToEdit:"Düzenlemek için tıkla",
  haveAnyQues:"Bu Şartların ilgili herhangi bir sorunuz varsa",
  contact:"TEMAS",
  address:"KAHVERENGİ KARTALI A.Ş.. \ N1000 N Batı Sokak \ nSuite 1200 \ nWilmington",
  registeredAddress:"Kayıtlı adres",
  Address:"Adres",
  city:"Kent",
  state:"Belirtmek, bildirmek",
  zipCode:"Posta kodu",
  country:"ülke",
  operationalAddress:"Operasyonel Adresi",
  companyInfo:"Şirket Bilgisi",
  website:"Web sitesi (örn: http://www.example.com)",
  established:"kurulmuş",
  employeeCount:"çalışan sayısı",
  description:"Şirket tanımı",
  emailNotVerified:"E-POSTA DEĞİL VERIFIED",
  verifyNow:"senin BrownEagle hesabınızı doğrulamak için DOĞRULA tıklayın",
  later:"Sonra",
  mainProducts:"Ana Ürünler",
  add:"EKLEMEK",
  keywordsEx:"(Örn: Anahtar Sözcük1",
  settingsTitle:"AYARLAR",
  TCTtile:"ŞARTLAR VE KOŞULLAR",
  contactUsTitle:"BİZİMLE İLETİŞİME GEÇİN",
  profileNotVerified:"PROFİL DOĞRULAMA BEKLEYEN",
  ok:"tamam",
  sameAsRegisteredAddress:"Kayıtlı adresi ile aynı",
  passwordResetMsg:"Şifrenizi sıfırlamak için",
  account:"hesap",
  payment:"Ödeme",
  sales:"Satış",
  support:"Destek",
  others:"Diğerleri",
  chooseDepartment:"Bölüm seçiniz",
  message:"Mesaj...",
  rfqTitle:"ALIŞ İSTEĞİ",
  searchRfq:"Arama TT",
  rfqDetailsTitle:"TT DETAYLARI",
  quantityRequired:"Miktar Gerekli",
  availability:"Kullanılabilirlik",
  datePosted:"tarihi Yayınlanan",
  detailedDescription:"Detaylı Açıklama",
  quoteNow:"ŞİMDİ ALINTILA",
  emailAlreadyExists:"Bu e-posta zaten var",
  enterValidEmail:"Geçerli bir e",
  passwordCannotBeEmpty:"Şifre boş olamaz",
  onlyBuyersCanLoggedIn:"Yalnızca alıcılar oturum olabilir.",
  enterValidName:"Lütfen geçerli bir isim giriniz",
  enterValidLastName:"Geçerli bir soyadı giriniz",
  enterValidContact:"Geçerli bir iletişim numarasını giriniz",
  passwordLengthError:"Şifre az 6 karakter olamaz",
  passwordNotMatched:"Şifreleriniz eşleşti didnot",
  noUserRegistered:"e-posta adresiyle kayıtlı kullanıcı yok",
  profileUpdatedSuccessfully:"Profil detayları başarıyla güncellendi",
  passwordUpdatedSuccessfully:"şifre başarıyla güncellendi",
  enterValidCompanyName:"Geçerli bir şirket adı girin",
  countryOrRegion:"Ülke / bölge",
  onlySellersCanLoggedin:"Sadece Kahverengi Kartal satıcıları kaydedilebilir olabilir.",
  fetchingLocation:"Konum getiriliyor ...",
  noCategoriesFound:"Hiçbir kategori bulunamadı",
  noSubcategoriesFound:"Hiçbir alt kategoriler bulundu",
  addressCannotBeEmpty:"Kayıtlı adresi boş olamaz",
  operationalAddressCannotBeEmpty:"Operasyonel adresi boş olamaz",
  websiteCannotBeEmpty:"Web sitesi boş olamaz",
  establishedCannotBeEmpty:"Şirket kurulmuş yıl boş olamaz",
  employeeCountCannotBeEmpty:"Çalışan sayısı boş olamaz",
  imageExceedsAlert:"Sen 6 görüntüleri kadar yükleyebilirsiniz.",
  quantity:"Quant",
  pieces:"birimler",
  piece:"birim",
  noRfqFound:"Hiçbir RFQs bulundu",
  subCategory:"Alt Kategorisi",
  unitPrice:"Birim fiyat",
  verified:"doğrulanmış",
  title:"Başlık",
  delete:"SİL",
  categoryTitle:"KATEGORİLER",
  sendQuotationsTitle:"GÖNDER TEKLİFİ",
  enterQuantity:"Bir miktar girin",
  enterUnitPrice:"Birim fiyatını girin",
  productDetail:"Ürün Detayları",
  sendProposal:"Bir Öneri Gönder",
  deliveryTime:"Teslimat süresi",
  enterDeliveryTime:"(Gün olarak) bir teslim saati girin",
  quotationsTitle:"MY Özlü",
  searchQuotations:"Arama Sözler",
  QUOTATIONS:"Özlü sözler",
  status:"durum",
  all:"Herşey",
  open:"Açık",
  rejected:"Reddedilen",
  closed:"Kapalı",
  sortBy:"Göre sırala",
  startDate:"Başlangıç ​​tarihi",
  endDate:"Bitiş tarihi",
  quotationDetalisTitle:"TEKLİF DETAYLARI",
  shopBy:"bazında alışveriş",
  enterTitle:"Bir başlık girin",
  minQuantity:"Asgari Miktar",
  quotedPrice:"Alıntı Fiyat",
  estimatedDeliveryTime:"Tahmini varış zamanı",
  enterMinQuantity:"Asgari quntity girin",
  enterEtimatedDeliveryTime:"Tahmini teslim zamanı girin",
  coverLetter:"Ön yazı",
  enterCoverLetter:"Bir kapak mektubu girin",
  pleaseEnterTitle:"Lütfen bir başlık girin",
  pleaseEnterMinQuantity:"minimum miktarda giriniz",
  pleaseEnterQuotedPrice:"Bir alıntı fiyatı girin",
  pleaseEnterEstimatedDeliveryTime:"Tahmini teslim süresi giriniz",
  pleaseEnterCoverLetter:"Bir kapak mektubu gönderin",
  quottionSubmittedSuccessfully:"Sizin tırnak başarıyla gönderildi",
  noQuotationsFound:"Hiçbir alıntılar bulundu",
  membershipPlan:"Yükseltme Planı",
  membershipPlanTitle:"ÜYELİK PLANI",
  expandBusiness:"Diyelim ki alıcılardan gelen acil güvenini kazanmak yardımcı olur Expand İş Let",
  chooseMembershipPackage:"Bir Üyelik Paketi Seç",
  noPackagesAtYourLocation:"Bulunduğunuz yerde yok planlar",
  package:"paket",
  storage:"Ayda Depolama",
  nextRenewal:"Sonraki Yenileme",
  expireOn:"Son kullanım tarihi",
  unSubscribePlan:"aboneliğini Planı",
  subscribePlan:"Planı Abone",
  subscribeConfirm:"Emin planı abone olmak istiyor musunuz?",
  unSubscribeConfirm:"Emin planı aboneliğinden çıkmak istiyor musunuz?",
  subscriptionFailed:"planı Aboneliği iptal edilemedi",
  productListing:"Toplam Ürün Listeleri",
  detailsTitle:"DETAYLAR",
  packageCost:"Paket Maliyeti",
  service:"Hizmet",
  serviceType:"servis tipi",
  serviceCost:"Servis bedeli",
  upgradeNow:"ŞİMDİ YÜKSELT",
  upload:"Yükleme",
  video:"Video",
  myCertificates:"Benim Sertifikalar",
  myCertificatesTitle:"MY BELGELERİ",
  noCertificatesUploaded:"Hayır Sertifikalar Yüklenen",
  addCertificate:"ADD BELGESİ",
  viewCertificateTitle:"GÖRÜNÜM",
  clickToView:"görüntülemek için tıkla",
  certificateTitle:"SERTİFİKA ADI",
  somethingWentWrong:"Bir şeyler yanlış gitti. Lütfen daha sonra tekrar deneyiniz",
  titleCannotBeEmpty:"Başlık boş olamaz",
  certificateUploadedSuccessfully:"Sertifikanız başarıyla yüklendi",
  myVideosTitle:"KAPAK VİDEO",
  myVideos:"Kapak video",
  noVideosUploaded:"Hiçbir kapak video bulunamadı",
  addVideo:"ŞİMDİ EKLE",
  canUploadOnlyOneVideo:"Yalnızca 1 video yükleyebilirsiniz",
  brownEagleWillCharge:"Kahverengi Kartal talep edecektir",
  commissionForThisCategory:"Bu kategori için komisyon",
  termsAndConditionsApplied:"Şartlar ve Koşullar Uygulamalı",
  noTermsFound:"Şartlar ve Koşullar uygulanmaz.",
  cannotAddThisCategory:"Henüz herhangi bir alt kategorilerini içermediğinden bu kategoriyi eklemek olamaz. Diğer kategoriler ekleyiniz.",
  allOrders:"Herşey",
  yearlyRfqLimit:"Yıllık RFQs sınırı",
  contactPersonDetails:"Muhatap Detayları",
  name:"ad",
  contactPersonCannotBeEmpty:"İletişim kişi ayrıntıları boş olamaz",
  quickDetails:"Hızlı Ayrıntılar",
  label:"Etiket",
  value:"değer",
  addMore:"Daha ekle",
  pending:"kadar",
  profileVerification:"Doğrulama Profil",
  profileApproval:"Profil Onayı",
  confirmed:"Onaylanan siparişler",
  shippedOrders:"gönderilen Siparişler",
  deliveredOrders:"teslim Siparişler",
  rejectedOrders:"Reddedilen Siparişler",
  cancelledOrders:"İptal Edilen Siparişler",
  noOrdersFound:"sipariş bulunamadı",
  checkout:"ÇIKIŞ YAPMAK",
  orderShippedd:"Sipariş sevk",
  confirmedd:"onaylı",
  cancelled:"İptal edildi",
  paymentSuccessfull:"ÖDEME BAŞARILI",
  allOrdersTitle:"TÜM SİPARİŞLER",
  from:"itibaren",
  minOrder:"Min. Sipariş",
  allOrders:"Herşey",
  waitingForContractDraft:"Sözleşme taslağı bekleniyor",
  waitingForOrderConfirmation:"sipariş onayı bekleniyor",
  waitingForPayment:"Ödeme için bekleniyor",
  waitingForPaymentConfirmation:"ödeme onayı bekleniyor",
  waitingForShipment:"Sevkiyat için bekleniyor",
  waitingForDeliveryConfirmation:"Teslimat onayı bekleniyor",
  orderCancelRequested:"Sipariş istenen iptal",
  disputeOrRefund:"Anlaşmazlık / İade",
  completed:"Tamamlanan",
  closed:"Kapalı",
  waitingForSupplier:"onayla sırasına tedarikçisi bekleniyor",
  waitingForPayment:"Ödeme için bekleniyor",
  shipped:"gönderilen",
  delivered:"teslim",
  productStatus:"ürün durumu",
  chat:"SOHBET",
  supplierAndProductInformation:"Tedarikçi ve Ürün Bilgileri",
  total:"Genel Toplam",
  orderDetails:"sipariş detayları",
  orderNumber:"Sipariş numarası",
  orderSubmitted:"Gönderilen Sipariş",
  cancelOrder:"İPTAL ETMEK",
  track:"IZLEMEK",
  trackOrderTitle:"PARCA SİPARİSİ",
  shippingAddress:"teslimat adresi",
  landmark:"işaret",
  buyerAndProductInformation:"Alıcı ve Ürün Bilgileri",
  reject:"REDDET",
  accept:"KABUL ETMEK",
  rejectOrder:"SİPARİŞ REDDET",
  acceptOrder:"SİPARİŞ KABUL",
  orderDetailsTitle:"SİPARİŞ DETAYLARI",
  track:"IZLEMEK",
  key:"anahtar",
  quickDetailsEx:"(Renk durabilmelerine: Siyah)",
  customerReviews:"Musteri degerlendirmeleri",
  customerReview:"Müşteri yorumu",
  allReviewsTitle:"TÜM YORUMLAR",
  productPreview:"Ürün Önizleme",
  show:"GÖSTERMEK",
  productPreviewTitle:"ÜRÜN ÖNİZLEME",
  supplierProfile:"tedarikçi Profili",
  view:"Görünüm",
  contactPerson:"İlgili kişi",
  ratingsReviews:"Oylar ve Yorumlar",
  recentlyAddedReviews:"Son eklenen yorumlar",
  thisProductHasNoReview:"Üzgünüm",
  days:"günler",
  perQuantity:"miktar başına",
  rfqDetails:"TT Detayları -",
  myQuotation:"Benim tırnak",
  inDays:"Günlerde",
  notAdded:"Eklenmez",
  viewTermsConditions:"Görünüm Koşulları",
  by:"tarafından",
  paymentSuccessfull:"ÖDEME BAŞARILI",
  planUpgradedSuccessfully:"Eğer planı yükseltilmiş",
  pleaseWaitPaymentMsg:"isteğinizin işlenmesi lütfen bekleyin ...",
  activePlan:"Aktif Planı",
  productUsed:"Ürün kullanılan",
  storageUsed:"Depolama kullanılan",
  storageRemaining:"Depolama kalan",
  rfqUsed:"TT kullanılan",
  rfqRemaining:"TT kalan",
  noActivePlan:"Herhangi üyelik planını satın almamış. alıcılardan derhal güvenini kazanmak yardımcı olan bir üyelik Paket seçiniz",
  sellerShare:"Satıcı Hisse",
  commission:"komisyon",
  productDimensions:"Ürün Boyutları",
  weight:"(Gram olarak) Ağırlık",
  width:"Genişlik (inç olarak)",
  height:"İnç olarak yükseklik)",
  depth:"(İnç olarak) derinliği",
  pleaseEnterDimensions:"Ürün boyutları ekleyiniz",
  myReferences:"Benim Kaynaklar",
  noReferencesAdded:"Hiçbir referanslar eklendi",
  addReferences:"ADD REFERANSLAR",
  clientInformation:"Müşteri bilgisi",
  shortNote:"Kısa bir not yazın",
  yourReferenceCreatedSuccessfully:"Referansınız başarıyla oluşturuldu",
  unableToOpen:"EDİLEMEDİ AÇIKTIR",
  urlIsNotCorrect:"URL doğru değil",
  yourReferenceSavedSuccessfully:"Referansınız başarıyla kaydedildi",
  orderPlaced:"Ödemeniz başarıyla yapılmıştır",
  shippingOrders:"emir Nakliye",
  payments:"Ödemeler",
  personalDetails:"Kişisel detaylar",
  companyDetails:"Şirket Detayları",
  kycSubmitConfirm:"Emin KYC formu göndermek istiyor musunuz?",
  kycSubmittedSuccessfully:"KYC başarıyla gönderildi. Biz Durumunuzu işlenen bir kez size bildirilir",
  packageDimensions:"Paket boyutları",
  length:"(İnç olarak) uzunluğu",
  units:"(Sayı olarak) Birimler",
  shippingOptions:"Nakliye Yöntemi",
  shippingCharges:"Masraflar Nakliye",
  listPrice:"Liste fiyatı",
  grandTotal:"Genel Toplam",
  productTermsConditions:"Ürün Şartları ve Koşulları",
  enterTermsConditions:"şartları ve koşulları girin"
}
